---
title: Benchmarking scMutrace and smartSeq
author: Qun Li
date: 13 Aug 2025 at 14:07:57
output:
  pdf_document: 
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

#ENV
```{r envs}
rm(list = ls())
setwd("/Users/liqun/Desktop/scMutraceReproducibility/Figure3/")
```

# Libraries
```{r libraries}
library(ggplot2)
library(ggpubr)
library(dplyr)
library(circlize)
library(ggVennDiagram)
library(ComplexHeatmap)
```

# Functions
```{r functions}
retriveCellsByLocation <- function(CSM, locList){
  CSM$CellTag <- rownames(CSM)
  CSM_tmp <- CSM[, c("CellTag",locList)]
  data_MutPerCell_CSM_tmp <- data.frame(
    CellTag = rownames(CSM_tmp),
    MutNum = rowSums(CSM_tmp == 1),
    WTNum = rowSums(CSM_tmp == 0)
  )
  cells_Total <- data_MutPerCell_CSM_tmp[rowSums(data_MutPerCell_CSM_tmp[,c("MutNum", "WTNum")]) > 0, ]$CellTag
  cells_WT <-    data_MutPerCell_CSM_tmp[data_MutPerCell_CSM_tmp[,"WTNum"] > 0,]$CellTag
  cells_Mut <-   data_MutPerCell_CSM_tmp[data_MutPerCell_CSM_tmp[,"MutNum"] > 0,]$CellTag
  cells <- list(Total = cells_Total, Mut = cells_Mut, WT = cells_WT)
  return(cells)
}

retriveLocsByCells <- function(CSM, cellList){
  CSM$CellTag <- rownames(CSM)
  CSM_tmp <- CSM[CSM$CellTag %in% cellList,]
  data_CellPerMut_CSM_tmp <- data.frame(
    Location = colnames(CSM_tmp),
    CellMutNum = colSums(CSM_tmp == 1),
    CellWTNum = colSums(CSM_tmp == 0)
  )
  pos_Total <- data_CellPerMut_CSM_tmp[rowSums(data_CellPerMut_CSM_tmp[, c("CellMutNum", "CellWTNum")]) > 0,]$Location
  pos_Mut <- data_CellPerMut_CSM_tmp[data_CellPerMut_CSM_tmp[, "CellMutNum"] > 0 ,]$Location
  pos_WT <- data_CellPerMut_CSM_tmp[data_CellPerMut_CSM_tmp[, "CellWTNum"] > 0 ,]$Location
  pos <- list(Total = pos_Total, Mut = pos_Mut, WT = pos_WT)
  return(pos)
}
```

# Load Data
```{r loadData}
data_CSM <- readRDS("../Data/SMARTSeq/data_CSM_NSCLC_SMARTSeq.rds")
data_CSM_TH179 <- data_CSM$TH179
data_CSM_TH179NAT <- data_CSM$TH179NAT
data_CSM_TH248 <- data_CSM$TH248

data_SSM <- readRDS("../Data/SMARTSeq/data_SSM_NSCLC_SMARTSeq.rds")
data_SSM_TH179_ann <- data_SSM$TH179
data_SSM_TH179NAT_ann <- data_SSM$TH179NAT
data_SSM_TH248_ann <- data_SSM$TH248

data_meta <- read.table("../Data/SMARTSeq/SMARTSeq_NSCLC_meta.txt", header = T, sep = "\t")
```

# Mutation burden
```{r Mutationburden}
# TH179
data_MutPerCell_TH179 <- data.frame(
  CellTag = rownames(data_CSM_TH179),
  MutNum_somatic = rowSums(data_CSM_TH179 == 1),
  WTNum_somatic = rowSums(data_CSM_TH179 == 0)
)

data_CellPerMut_TH179 <- data.frame(
  Location = colnames(data_CSM_TH179),
  CellMutNum = colSums(data_CSM_TH179 == 1),
  CellWTNum = colSums(data_CSM_TH179 == 0)
)

data_MutPerCell_TH179_ann <- merge(data_MutPerCell_TH179, data_meta, by = "CellTag")

# TH179NAT
data_MutPerCell_TH179NAT <- data.frame(
  CellTag = rownames(data_CSM_TH179NAT),
  MutNum_somatic = rowSums(data_CSM_TH179NAT == 1),
  WTNum_somatic = rowSums(data_CSM_TH179NAT == 0)
)

data_CellPerMut_TH179NAT <- data.frame(
  Location = colnames(data_CSM_TH179NAT),
  CellMutNum = colSums(data_CSM_TH179NAT == 1),
  CellWTNum = colSums(data_CSM_TH179NAT == 0)
)

data_MutPerCell_TH179NAT_ann <- merge(data_MutPerCell_TH179NAT, data_meta, by = "CellTag")

# TH248
data_MutPerCell_TH248 <- data.frame(
  CellTag = rownames(data_CSM_TH248),
  MutNum_somatic = rowSums(data_CSM_TH248 == 1),
  WTNum_somatic = rowSums(data_CSM_TH248 == 0)
)

data_CellPerMut_TH248 <- data.frame(
  Location = colnames(data_CSM_TH248),
  CellMutNum = colSums(data_CSM_TH248 == 1),
  CellWTNum = colSums(data_CSM_TH248 == 0)
)

data_MutPerCell_TH248_ann <- merge(data_MutPerCell_TH248, data_meta, by = "CellTag")

# comparision
my_comparisons_0 <- list(c("cancer", "noncancer"))


my_comparisons_00 <- list(c("cancer", "noncancer"),
                          c("cancer", "normal"))

my_comparisons_1 <- list(c("LT_S58_cancer", "LT_S58_noncancer"),
                       c("LT_S79_cancer", "LT_S79_noncancer"), 
                       c("LT_S80_cancer", "LT_S80_noncancer"))

my_comparisons_11 <- list(c("LT_S58_cancer", "LT_S58_noncancer"),
                       c("LT_S79_cancer", "LT_S79_noncancer"), 
                       c("LT_S80_cancer", "LT_S80_noncancer"),
                       c("LT_S58_cancer", "LT_S78_normal"),
                       c("LT_S79_cancer", "LT_S78_normal"), 
                       c("LT_S80_cancer", "LT_S78_normal"),
                       c("LT_S58_noncancer", "LT_S78_normal"),
                       c("LT_S79_noncancer", "LT_S78_normal"),
                       c("LT_S80_noncancer", "LT_S78_normal"))

my_comparisons_2 <- list(c("LT_S69_cancer", "LT_S69_noncancer"), 
                         c("LT_S74_cancer", "LT_S74_noncancer"))

my_comparisons_3 <- list(c("LT_S58_cancer", "LT_S58_noncancer"),
                       c("LT_S79_cancer", "LT_S79_noncancer"), 
                       c("LT_S80_cancer", "LT_S80_noncancer"),
                       c("LT_S58_cancer", "LT_S78_normal"),
                       c("LT_S79_cancer", "LT_S78_normal"), 
                       c("LT_S80_cancer", "LT_S78_normal"),
                       c("LT_S58_noncancer", "LT_S78_normal"),
                       c("LT_S79_noncancer", "LT_S78_normal"),
                       c("LT_S80_noncancer", "LT_S78_normal"),
                       c("LT_S69_cancer", "LT_S69_noncancer"), 
                       c("LT_S74_cancer", "LT_S74_noncancer"))

data_MutPerCell_TH179_TH179NAT_ann <- rbind(data_MutPerCell_TH179_ann, data_MutPerCell_TH179NAT_ann)
data_MutPerCell_TH179_TH179NAT_ann$type <- factor(data_MutPerCell_TH179_TH179NAT_ann$type, levels = c("cancer", "noncancer", "normal"))
data_MutPerCell_TH179_TH179NAT_ann$sampleCellType <- factor(data_MutPerCell_TH179_TH179NAT_ann$sampleCellType, levels = c("LT_S58_cancer", "LT_S58_noncancer",
                                                                                                                          "LT_S79_cancer", "LT_S79_noncancer",
                                                                                                                          "LT_S80_cancer", "LT_S80_noncancer", "LT_S78_normal"))

p_TH179_cancer_noncancer <- ggplot(data_MutPerCell_TH179_ann, aes(x=as.factor(type), y=MutNum_somatic, fill=as.factor(type))) + 
  geom_boxplot(outliers = FALSE) + 
  geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("cancer" = "#ca0020", 
                               "noncancer" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_0, 
                     method = "wilcox.test", 
                     label = "p.format")

p_TH179_TH179NAT_cancer_noncancer <- ggplot(data_MutPerCell_TH179_TH179NAT_ann, aes(x=as.factor(type), y=MutNum_somatic, fill=as.factor(type))) + 
  geom_boxplot(outliers = FALSE) + 
  geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("cancer" = "#ca0020", 
                               "noncancer" = "#d9d9d9",
                               "normal" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_00, 
                     method = "wilcox.test", 
                     label = "p.format")

p_TH248_cancer_noncancer <- ggplot(data_MutPerCell_TH248_ann, aes(x=as.factor(type), y=MutNum_somatic, fill=as.factor(type))) + 
  geom_boxplot(outliers = FALSE) + 
  geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("cancer" = "#ca0020", 
                               "noncancer" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_0, 
                     method = "wilcox.test", 
                     label = "p.format")

p_TH179_sampleCellType <- ggplot(data_MutPerCell_TH179_ann, aes(x=as.factor(sampleCellType), y=MutNum_somatic, fill=as.factor(sampleCellType))) + 
  geom_boxplot(outliers = FALSE) + 
  geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("LT_S58_cancer" = "#ca0020", 
                               "LT_S58_noncancer" = "#d9d9d9",
                               "LT_S79_cancer" = "#ca0020",
                               "LT_S79_noncancer" = "#d9d9d9",
                               "LT_S80_cancer" = "#ca0020",
                               "LT_S80_noncancer" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_1, 
                     method = "wilcox.test", 
                     label = "p.format")

p_TH179_TH179NAT_sampleCellType <- ggplot(data_MutPerCell_TH179_TH179NAT_ann, aes(x=as.factor(sampleCellType), y=MutNum_somatic, fill=as.factor(sampleCellType))) + 
  geom_boxplot(outliers = FALSE) + 
  geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("LT_S58_cancer" = "#ca0020", 
                               "LT_S58_noncancer" = "#d9d9d9",
                               "LT_S79_cancer" = "#ca0020",
                               "LT_S79_noncancer" = "#d9d9d9",
                               "LT_S80_cancer" = "#ca0020",
                               "LT_S80_noncancer" = "#d9d9d9",
                               "LT_S78_normal" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_11, 
                     method = "wilcox.test", 
                     label = "p.format")

p_TH248_sampleCellType <- ggplot(data_MutPerCell_TH248_ann, aes(x=as.factor(sampleCellType), y=MutNum_somatic, fill=as.factor(sampleCellType))) + 
  geom_boxplot(outliers = FALSE) + 
  geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("LT_S69_cancer" = "#ca0020", 
                               "LT_S69_noncancer" = "#d9d9d9",
                               "LT_S74_cancer" = "#ca0020",
                               "LT_S74_noncancer" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_2, 
                     method = "wilcox.test", 
                     label = "p.format")

data_MutPerCell_TH248_TH179_TH179NAT_ann_ <- rbind(data_MutPerCell_TH248_ann, data_MutPerCell_TH179_TH179NAT_ann)

data_MutPerCell_TH248_TH179_TH179NAT_ann_$sampleCellType <- factor(data_MutPerCell_TH248_TH179_TH179NAT_ann_$sampleCellType,
                                                                   levels = c("LT_S74_cancer", "LT_S74_noncancer",
                                                                              "LT_S69_cancer", "LT_S69_noncancer",
                                                                              "LT_S58_cancer", "LT_S58_noncancer",
                                                                              "LT_S79_cancer", "LT_S79_noncancer",
                                                                              "LT_S80_cancer", "LT_S80_noncancer",
                                                                              "LT_S78_normal"))
p_TH248_TH179_TH179NAT_sampleCellType <- ggplot(data_MutPerCell_TH248_TH179_TH179NAT_ann_, aes(x=as.factor(sampleCellType), y=MutNum_somatic, fill=as.factor(sampleCellType))) + 
  geom_boxplot(outliers = FALSE) + 
  #geom_jitter(width=0.2, size=1, alpha=0.5) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = c("LT_S69_cancer" = "#ca0020", 
                               "LT_S69_noncancer" = "#d9d9d9",
                               "LT_S74_cancer" = "#ca0020",
                               "LT_S74_noncancer" = "#d9d9d9",
                               "LT_S58_cancer" = "#ca0020", 
                               "LT_S58_noncancer" = "#d9d9d9",
                               "LT_S79_cancer" = "#ca0020",
                               "LT_S79_noncancer" = "#d9d9d9",
                               "LT_S80_cancer" = "#ca0020",
                               "LT_S80_noncancer" = "#d9d9d9",
                               "LT_S78_normal" = "#d9d9d9")) +
  stat_compare_means(comparisons = my_comparisons_3, 
                     method = "wilcox.test", 
                     label = "p.format")

p_TH179_cancer_noncancer
p_TH179_TH179NAT_cancer_noncancer
p_TH248_cancer_noncancer
p_TH179_sampleCellType

p_TH179_TH179NAT_sampleCellType
p_TH248_sampleCellType
p_TH248_TH179_TH179NAT_sampleCellType

pdf("../Figures/SMARTSeq/p_TH179_TH179NAT_sampleCellType_Mut.pdf", )
p_TH179_TH179NAT_sampleCellType
dev.off()

pdf("../Figures/SMARTSeq/p_TH248_sampleCellType_Mut.pdf", )
p_TH248_sampleCellType
dev.off()

pdf("../Figures/SMARTSeq/p_TH248_TH179_TH179NAT_sampleCellType_Mut.pdf", width = 5.17, height = 3.73)
p_TH248_TH179_TH179NAT_sampleCellType
dev.off()
```


# Benchmarking
```{r benchmarking}
data_benchmarking <- read.table("../Data/SMARTSeq/data_benchmarking_NSCLC.txt", sep = "\t", header = T)
data_benchmarking_meta <- merge(data_benchmarking, data_meta, by = "CellTag")
data_benchmarking_meta$Gene <- sub("_.*", "", data_benchmarking_meta$Mutation)

mutations_benchmarking <- c("BRAF_V600E", "BRCA2_N372H", "DROSHA_S321L", "EGFR_K745_A750_T", "ROS1_K2228Q", "ROS1_S2229C", "TP53_P72R")
col_benchmarking <- c("Mutation", "Precision", "Recall", "F1Score")

data_benchmarking_res <- as.data.frame(matrix(data = 0, nrow = length(mutations_benchmarking), ncol = length(col_benchmarking)))
colnames(data_benchmarking_res) <- col_benchmarking

for (i in 1:length(mutations_benchmarking)){
  mut <- mutations_benchmarking[i]
  cell_smart <- data_benchmarking_meta[data_benchmarking_meta$Mutation == mut & data_benchmarking_meta$Type == "smartSeq",]$cell_id
  cell_scmut <- data_benchmarking_meta[data_benchmarking_meta$Mutation == mut & data_benchmarking_meta$Type == "scMut",]$cell_id
  cell_commo <- intersect(cell_smart, cell_scmut)
  precision <- length(cell_commo) / length(cell_scmut)
  recall <- length(cell_commo) / length(cell_smart)
  f1score <- (2 * precision * recall)/(precision + recall)
  data_benchmarking_res[i,]$Mutation <- mut
  data_benchmarking_res[i,]$Precision <- precision
  data_benchmarking_res[i,]$Recall <- recall
  data_benchmarking_res[i,]$F1Score <- f1score
}

genesColor <- c(BRAF_V600E = "#1f78b4",
                BRCA2_N372H = "#33a02c",
                DROSHA_S321L = "#e31a1c",
                EGFR_K745_A750_T = "#ff7f00",
                ROS1_K2228Q = "#6a3d9a",
                ROS1_S2229C = "#ffff99",
                TP53_P72R = "#b15928")

p_benchmarking <- ggplot(data = data_benchmarking_res) + geom_point(mapping =  aes(x = Recall , y = Precision, color = Mutation), size = 10, show.legend = TRUE) +
  scale_color_manual(values = genesColor) +
  xlab("Recall") + ylab("Precision") + 
  xlim(0, 1) +
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.title = element_text(size=20), axis.text.y = element_text(size=20),
          axis.text.x = element_text(size=20), legend.text=element_text(size=15))

p_benchmarking

venn_list_TP53_P72R <- list(scMut = unique(data_benchmarking_meta %>% filter(Mutation == "TP53_P72R" & Type == "scMut") %>% pull(CellTag)), 
                            GATK = unique(data_benchmarking_meta %>% filter(Mutation == "TP53_P72R" & Type == "smartSeq") %>% pull(CellTag)))

p_venn_TP53_P72R <- ggVennDiagram(venn_list_TP53_P72R, category.names = c("scMut", "GATK")) + scale_fill_distiller(palette = "RdBu")
p_venn_TP53_P72R

pdf("../Figures/SMARTSeq/p_benchmarking.pdf", width = 8.21, height = 4.75)
p_benchmarking
dev.off()

pdf("../Figures/SMARTSeq/p_venn_TP53_P72R.pdf", width = 8.21, height = 4.75)
p_venn_TP53_P72R
dev.off()

write.csv(data_benchmarking_res, "../Data/SMARTSeq/Benchmarking_data.csv")
```

# Census genes celltypelevel
```{r censusgenescelltypelevel}
# from COSMIC database
# TP53 from original paper
data_cencusgenes <- c("AKT1", "ALK", "BAP1", "BRAF", "CCDC6", "CD74", "DDR2", 
                      "DROSHA", "EGFR", "EML4", "ERBB2", "ERBB4", "EZR", 
                      "FGFR2", "GOLPH3", "HIP1", "KDR", "KEAP1", "KIF5B", 
                      "LRIG3", "MAP2K1", "MAP2K2", "NFE2L2", "NKX2-1", 
                      "NRG1", "PIK3CB", "PTPN13", "RET", "ROS1", "SDC4", 
                      "SMARCA4", "SOX2", "STK11", "TFG", "TPM3", "TPR", "TP53")

data_SSM_TH179_ann_selected <- data_SSM_TH179_ann[data_SSM_TH179_ann$Gene.refGene %in% data_cencusgenes & data_SSM_TH179_ann$Func.refGene %in% c("splicing", "exonic"),]
data_SSM_TH179NAT_ann_selected <- data_SSM_TH179NAT_ann[data_SSM_TH179NAT_ann$Gene.refGene %in% data_cencusgenes & data_SSM_TH179NAT_ann$Func.refGene %in% c("splicing", "exonic"),]
data_SSM_TH248_ann_selected <- data_SSM_TH248_ann[data_SSM_TH248_ann$Gene.refGene %in% data_cencusgenes & data_SSM_TH248_ann$Func.refGene %in% c("splicing", "exonic"),]

census_genes <- unique(c(data_SSM_TH179_ann_selected$Gene.refGene, data_SSM_TH248_ann_selected$Gene.refGene, data_SSM_TH179NAT_ann_selected$Gene.refGene))

# TH179
cells_LT_S58_cancer <- data_meta[data_meta$sample_name == "LT_S58" & data_meta$type == "cancer",]$CellTag
cells_LT_S58_noncancer <- data_meta[data_meta$sample_name == "LT_S58" & data_meta$type == "noncancer",]$CellTag
cells_LT_S79_cancer <- data_meta[data_meta$sample_name == "LT_S79" & data_meta$type == "cancer",]$CellTag
cells_LT_S79_noncancer <- data_meta[data_meta$sample_name == "LT_S79" & data_meta$type == "noncancer",]$CellTag
cells_LT_S80_cancer <- data_meta[data_meta$sample_name == "LT_S80" & data_meta$type == "cancer",]$CellTag
cells_LT_S80_noncancer <- data_meta[data_meta$sample_name == "LT_S80" & data_meta$type == "noncancer",]$CellTag

# TH248
cells_LT_S69_cancer <- data_meta[data_meta$sample_name == "LT_S69" & data_meta$type == "cancer",]$CellTag
cells_LT_S69_noncancer <- data_meta[data_meta$sample_name == "LT_S69" & data_meta$type == "noncancer",]$CellTag
cells_LT_S74_cancer <- data_meta[data_meta$sample_name == "LT_S74" & data_meta$type == "cancer",]$CellTag
cells_LT_S74_noncancer <- data_meta[data_meta$sample_name == "LT_S74" & data_meta$type == "noncancer",]$CellTag

# TH249NAT
cells_TH179_NAT_normal <- data_meta[data_meta$patient_id == "TH179_NAT" & data_meta$type == "normal",]$CellTag

col_fra <- c("LT_S58_cancer", "LT_S58_noncancer", "LT_S79_cancer", "LT_S79_noncancer",
             "LT_S80_cancer", "LT_S80_noncancer", "LT_S69_cancer", "LT_S69_noncancer",
             "LT_S74_cancer", "LT_S74_noncancer", "TH179_NAT")

data_census_fraction <- as.data.frame(matrix(data = 0, nrow = length(census_genes), ncol = length(col_fra)))
rownames(data_census_fraction) <- census_genes
colnames(data_census_fraction) <- col_fra

genes_TH179 <- unique(data_SSM_TH179_ann_selected$Gene.refGene)
genes_TH179NAT <- unique(data_SSM_TH179NAT_ann_selected$Gene.refGene)
genes_TH248 <- unique(data_SSM_TH248_ann_selected$Gene.refGene)


for (i in seq_along(census_genes)) {
  gene <- census_genes[i]
  #data_census_fraction[i, "gene"] <- gene
  
  # TH179
  if (gene %in% genes_TH179) {
    sites_TH179 <- data_SSM_TH179_ann_selected[data_SSM_TH179_ann_selected$Gene.refGene == gene, "Mutation"]
    cells_TH179 <- retriveCellsByLocation(data_CSM_TH179, sites_TH179)$Mut
    
    data_census_fraction[i, "LT_S58_cancer"]    <- length(intersect(cells_LT_S58_cancer, cells_TH179)) / length(cells_LT_S58_cancer)
    data_census_fraction[i, "LT_S58_noncancer"] <- length(intersect(cells_LT_S58_noncancer, cells_TH179)) / length(cells_LT_S58_noncancer)
    data_census_fraction[i, "LT_S79_cancer"]    <- length(intersect(cells_LT_S79_cancer, cells_TH179)) / length(cells_LT_S79_cancer)
    data_census_fraction[i, "LT_S79_noncancer"] <- length(intersect(cells_LT_S79_noncancer, cells_TH179)) / length(cells_LT_S79_noncancer)
    data_census_fraction[i, "LT_S80_cancer"]    <- length(intersect(cells_LT_S80_cancer, cells_TH179)) / length(cells_LT_S80_cancer)
    data_census_fraction[i, "LT_S80_noncancer"] <- length(intersect(cells_LT_S80_noncancer, cells_TH179)) / length(cells_LT_S80_noncancer)
  }
  
  # TH248
  if (gene %in% genes_TH248) {
    sites_TH248 <- data_SSM_TH248_ann_selected[data_SSM_TH248_ann_selected$Gene.refGene == gene, "Mutation"]
    cells_TH248 <- retriveCellsByLocation(data_CSM_TH248, sites_TH248)$Mut
    
    data_census_fraction[i, "LT_S69_cancer"]    <- length(intersect(cells_LT_S69_cancer, cells_TH248)) / length(cells_LT_S69_cancer)
    data_census_fraction[i, "LT_S69_noncancer"] <- length(intersect(cells_LT_S69_noncancer, cells_TH248)) / length(cells_LT_S69_noncancer)
    data_census_fraction[i, "LT_S74_cancer"]    <- length(intersect(cells_LT_S74_cancer, cells_TH248)) / length(cells_LT_S74_cancer)
    data_census_fraction[i, "LT_S74_noncancer"] <- length(intersect(cells_LT_S74_noncancer, cells_TH248)) / length(cells_LT_S74_noncancer)
  }
  
  # TH179_NAT
  if (gene %in% genes_TH179NAT) {
    sites_TH179NAT <- data_SSM_TH179NAT_ann_selected[data_SSM_TH179NAT_ann_selected$Gene.refGene == gene, "Mutation"]
    cells_TH179NAT <- retriveCellsByLocation(data_CSM_TH179NAT, sites_TH179NAT)$Mut
    
    data_census_fraction[i, "TH179_NAT"] <- length(intersect(cells_TH179_NAT_normal, cells_TH179NAT)) / length(cells_TH179_NAT_normal)
  }
}

max_val <- max(data_census_fraction)

col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))

p_proportion <- pheatmap(data_census_fraction, 
                         cluster_rows = FALSE, 
                         cluster_cols = FALSE, 
                         cellwidth = 20, 
                         cellheight = 20,
                         display_numbers = TRUE,
                         number_color = "white",
                         border_color = "white",
                         color = col_fun_v1)

p_proportion

pdf("../Figures/SMARTSeq/p_proportion_cellType.pdf", width = 8.21, height = 5.04)
p_proportion
dev.off()
```

# Census genes samplelevel
```{r censusgenessamplelevel}
# from COSMIC database
# TP53 from original paper
data_cencusgenes <- c("AKT1", "ALK", "BAP1", "BRAF", "CCDC6", "CD74", "DDR2", 
                      "DROSHA", "EGFR", "EML4", "ERBB2", "ERBB4", "EZR", 
                      "FGFR2", "GOLPH3", "HIP1", "KDR", "KEAP1", "KIF5B", 
                      "LRIG3", "MAP2K1", "MAP2K2", "NFE2L2", "NKX2-1", 
                      "NRG1", "PIK3CB", "PTPN13", "RET", "ROS1", "SDC4", 
                      "SMARCA4", "SOX2", "STK11", "TFG", "TPM3", "TPR", "TP53")

data_SSM_TH179_ann_selected <- data_SSM_TH179_ann[data_SSM_TH179_ann$Gene.refGene %in% data_cencusgenes & data_SSM_TH179_ann$Func.refGene %in% c("splicing", "exonic"),]
data_SSM_TH179NAT_ann_selected <- data_SSM_TH179NAT_ann[data_SSM_TH179NAT_ann$Gene.refGene %in% data_cencusgenes & data_SSM_TH179NAT_ann$Func.refGene %in% c("splicing", "exonic"),]
data_SSM_TH248_ann_selected <- data_SSM_TH248_ann[data_SSM_TH248_ann$Gene.refGene %in% data_cencusgenes & data_SSM_TH248_ann$Func.refGene %in% c("splicing", "exonic"),]

census_genes <- unique(c(data_SSM_TH179_ann_selected$Gene.refGene, data_SSM_TH248_ann_selected$Gene.refGene, data_SSM_TH179NAT_ann_selected$Gene.refGene))

# TH179
cells_LT_S58 <- data_meta[data_meta$sample_name == "LT_S58",]$CellTag
cells_LT_S79 <- data_meta[data_meta$sample_name == "LT_S79",]$CellTag
cells_LT_S80 <- data_meta[data_meta$sample_name == "LT_S80",]$CellTag


# TH248
cells_LT_S69 <- data_meta[data_meta$sample_name == "LT_S69",]$CellTag
cells_LT_S74 <- data_meta[data_meta$sample_name == "LT_S74",]$CellTag

# TH249NAT
cells_TH179_NAT_normal <- data_meta[data_meta$patient_id == "TH179_NAT",]$CellTag

col_fra <- c("S74_GATK", "S69_GATK", 
             "S58_GATK", "S79_GATK",
             "S80_GATK", "NAT_GATK",
             "S74", "S69",
             "S58", "S79",
             "S80", "NAT")

data_census_fraction_sample <- as.data.frame(matrix(data = 0, nrow = length(census_genes), ncol = length(col_fra)))
rownames(data_census_fraction_sample) <- census_genes
colnames(data_census_fraction_sample) <- col_fra

genes_TH179 <- unique(data_SSM_TH179_ann_selected$Gene.refGene)
genes_TH179NAT <- unique(data_SSM_TH179NAT_ann_selected$Gene.refGene)
genes_TH248 <- unique(data_SSM_TH248_ann_selected$Gene.refGene)

for (i in seq_along(census_genes)) {
  gene <- census_genes[i]
  
  # TH179
  if (gene %in% genes_TH179) {
    sites_TH179 <- data_SSM_TH179_ann_selected[data_SSM_TH179_ann_selected$Gene.refGene == gene, "Mutation"]
    cells_TH179 <- retriveCellsByLocation(data_CSM_TH179, sites_TH179)$Mut
    cells_TH179_GATK <- data_benchmarking_meta %>% filter(Type == "smartSeq" & patient_id == "TH179" & Gene == gene) %>% pull(CellTag)
    
    data_census_fraction_sample[i, "S58"]    <- length(intersect(cells_LT_S58, cells_TH179)) / length(cells_LT_S58)
    data_census_fraction_sample[i, "S79"]    <- length(intersect(cells_LT_S79, cells_TH179)) / length(cells_LT_S79)
    data_census_fraction_sample[i, "S80"]    <- length(intersect(cells_LT_S80, cells_TH179)) / length(cells_LT_S80)
    
    if (length(cells_TH179_GATK) > 0){
      data_census_fraction_sample[i, "S58_GATK"]    <- length(intersect(cells_LT_S58, cells_TH179_GATK)) / length(cells_LT_S58)
      data_census_fraction_sample[i, "S79_GATK"]    <- length(intersect(cells_LT_S79, cells_TH179_GATK)) / length(cells_LT_S79)
      data_census_fraction_sample[i, "S80_GATK"]    <- length(intersect(cells_LT_S80, cells_TH179_GATK)) / length(cells_LT_S80)
    }
  }
  
  # TH248
  if (gene %in% genes_TH248) {
    sites_TH248 <- data_SSM_TH248_ann_selected[data_SSM_TH248_ann_selected$Gene.refGene == gene, "Mutation"]
    cells_TH248 <- retriveCellsByLocation(data_CSM_TH248, sites_TH248)$Mut
    cells_TH248_GATK <- data_benchmarking_meta %>% filter(Type == "smartSeq" & patient_id == "TH248" & Gene == gene) %>% pull(CellTag)
    
    data_census_fraction_sample[i, "S69"]    <- length(intersect(cells_LT_S69, cells_TH248)) / length(cells_LT_S69)
    data_census_fraction_sample[i, "S74"]    <- length(intersect(cells_LT_S74, cells_TH248)) / length(cells_LT_S74)
    
    if (length(cells_TH248_GATK) > 0){
      data_census_fraction_sample[i, "S69_GATK"]    <- length(intersect(cells_LT_S69, cells_TH248_GATK)) / length(cells_LT_S69)
      data_census_fraction_sample[i, "S74_GATK"]    <- length(intersect(cells_LT_S74, cells_TH248_GATK)) / length(cells_LT_S74)
    }
  }
  
  # TH179_NAT
  if (gene %in% genes_TH179NAT) {
    sites_TH179NAT <- data_SSM_TH179NAT_ann_selected[data_SSM_TH179NAT_ann_selected$Gene.refGene == gene, "Mutation"]
    cells_TH179NAT <- retriveCellsByLocation(data_CSM_TH179NAT, sites_TH179NAT)$Mut
    
    data_census_fraction_sample[i, "NAT"] <- length(intersect(cells_TH179_NAT_normal, cells_TH179NAT)) / length(cells_TH179_NAT_normal)
  }
}

max_val <- max(data_census_fraction_sample)

col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))

p_proportion_sample <- pheatmap(data_census_fraction_sample, 
                         cluster_rows = FALSE, 
                         cluster_cols = FALSE, 
                         cellwidth = 20, 
                         cellheight = 20,
                         display_numbers = TRUE,
                         number_color = "white",
                         border_color = "white",
                         color = col_fun_v1)

p_proportion_sample

pdf("../Figures/SMARTSeq/p_proportion_sample.pdf", width = 8.21, height = 5.04)
p_proportion_sample
dev.off()

write.csv(data_census_fraction_sample, "../Data/SMARTSeq/Mutation_sample.csv")
```
# GermlinePopulation
```{r population}
data_population <- readRDS("../Data/SMARTSeq/data_populationData_NSCLC.rds")
data_1kgenome_ann <- read.table("../Data/SMARTSeq/1000genomeSampleInfo.txt", header = T, sep = "\t")
TH179_population_count <- data_population$TH179Count
TH179_population_fraq <- data_population$TH179Fraq

TH179NAT_population_count <- data_population$TH179NATCount
TH179NAT_population_fraq <- data_population$TH179NATFraq

TH248_population_count <- data_population$Th248Count
TH248_population_fraq <- data_population$Th248Fraq

length(colnames(TH179_population_count))
sum(colnames(TH179_population_count) == colnames(TH248_population_count))
sum(colnames(TH179NAT_population_count) == colnames(TH248_population_count))

meta_population <- setdiff(colnames(TH179_population_fraq), c("male", "female"))

sample_size <- 100
fraq_threshold <- 0.3
iteration_times <- 5000

data_count_sexPopulation_TH179_resample <- as.data.frame(
  matrix(data = 0, nrow = iteration_times, ncol = length(meta_population))
)
colnames(data_count_sexPopulation_TH179_resample) <- meta_population

data_count_sexPopulation_TH179NAT_resample <- as.data.frame(
  matrix(data = 0, nrow = iteration_times, ncol = length(meta_population))
)
colnames(data_count_sexPopulation_TH179NAT_resample) <- meta_population

data_count_sexPopulation_TH248_resample <- as.data.frame(
  matrix(data = 0, nrow = iteration_times, ncol = length(meta_population))
)
colnames(data_count_sexPopulation_TH248_resample) <- meta_population

set.seed(2025)

for (i in 1:iteration_times){
  selected_nrows <- sample(1:nrow(TH179_population_fraq), sample_size, replace = FALSE)
  selected_data <- TH179_population_fraq[selected_nrows, meta_population]
  data_count_sexPopulation_TH179_resample[i, ] <- colSums(selected_data > fraq_threshold)
}

for (i in 1:iteration_times){
  selected_nrows <- sample(1:nrow(TH179NAT_population_fraq), sample_size, replace = FALSE)
  selected_data <- TH179NAT_population_fraq[selected_nrows, meta_population]
  data_count_sexPopulation_TH179NAT_resample[i, ] <- colSums(selected_data > fraq_threshold)
}

for (i in 1:iteration_times){
  selected_nrows <- sample(1:nrow(TH248_population_fraq), sample_size, replace = FALSE)
  selected_data <- TH248_population_fraq[selected_nrows, meta_population]
  data_count_sexPopulation_TH248_resample[i, ] <- colSums(selected_data > fraq_threshold)
}


medians <- apply(data_count_sexPopulation_TH179_resample, 2, median)
sorted_cols <- names(sort(medians, decreasing = TRUE))

boxplot(data_count_sexPopulation_TH179_resample[, sorted_cols],
        las = 2,                    
        col = "#bababa",  
        ylab = "Number of High-Frequency Mutations",
        main = "Resampled Mutation Frequencies Across Populations")

pdf("../Figures/SMARTSeq/p_TH179_resample_population.pdf", width = 8.21, height = 5.04)
boxplot(data_count_sexPopulation_TH179_resample[, sorted_cols],
        las = 2,                    
        col = "#bababa",  
        ylab = "Number of High-Frequency Mutations",
        main = "Resampled Mutation Frequencies Across Populations")
dev.off()

medians <- apply(data_count_sexPopulation_TH179NAT_resample, 2, median)
sorted_cols <- names(sort(medians, decreasing = TRUE))

boxplot(data_count_sexPopulation_TH179NAT_resample[, sorted_cols],
        las = 2,                    
        col = "#bababa",  
        ylab = "Number of High-Frequency Mutations",
        main = "Resampled Mutation Frequencies Across Populations")
dev.off()

pdf("../Figures/SMARTSeq/p_TH179NAT_resample_population.pdf", width = 8.21, height = 5.04)
boxplot(data_count_sexPopulation_TH179NAT_resample[, sorted_cols],
        las = 2,                    
        col = "#bababa",  
        ylab = "Number of High-Frequency Mutations",
        main = "Resampled Mutation Frequencies Across Populations")
dev.off()

medians <- apply(data_count_sexPopulation_TH248_resample, 2, median)
sorted_cols <- names(sort(medians, decreasing = TRUE))
boxplot(data_count_sexPopulation_TH248_resample[, sorted_cols],
        las = 2,                    
        col = "#bababa",  
        ylab = "Number of High-Frequency Mutations",
        main = "Resampled Mutation Frequencies Across Populations")

pdf("../Figures/SMARTSeq/p_TH248_resample_population.pdf", width = 8.21, height = 5.04)
boxplot(data_count_sexPopulation_TH248_resample[, sorted_cols],
        las = 2,                    
        col = "#bababa",  
        ylab = "Number of High-Frequency Mutations",
        main = "Resampled Mutation Frequencies Across Populations")
dev.off()
```
# sessionInfo
```{r sessionInfo}
sessionInfo()
```







