---
title: "Benchmarking scMutrace and XVseq"
author: "Qun Li"
date: "12 Aug 2025 at 14:05:26"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
  html_document:
    toc: true
    toc_depth: '3'
    df_print: paged
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Envs
```{r envs}
rm(list = ls())
setwd("/Users/liqun/Desktop/scMutrace-tutorial/ReproducibilityAnalysis/Figure3/")
```

# Libraries
```{r libraries}
library(ggplot2)
library(reshape2)
library(patchwork)
library(pheatmap)
library(ggVennDiagram)
library(ComplexHeatmap)
library(ggpubr)
library(dplyr)
library(tidyr)
library(tibble)
library(circlize)
library(gridExtra)
library(data.table)
```

# Load Data
```{r loadData}
# 0-wildtype, 1-mutant, 2-no call
data_XVSeq_raw <- read.table("../Data/HumanBPDCN/XVseq_PDC_meta.txt", header = T, sep = "\t")
# 0-wildtype, 1-mutant
data_scMut_raw <- read.table("../Data/HumanBPDCN/scMutrace_PDC_meta.txt", header = T, sep = "\t")
```

# Process data
```{r compareScmutracewithXVseq}
# data format
data_XVSeq <- reshape2::melt(
  data_XVSeq_raw,
  id.vars = c("cell", "replicate", "stage"),
  measure.vars = c("ACAP2", "CWF19L2", "HNRNPUL1", "RPS24",
                   "SMARCD1", "TET2_H1380Y", "TET2_Q1034",
                   "TET2_R1216", "TET2_S792"),
  variable.name = "gene",
  value.name = "mutInfo_XVseq"
)

data_scMut <- data_scMut_raw

data_XVSeq$tag <- paste(data_XVSeq$replicate, data_XVSeq$gene, data_XVSeq$cell, sep = "_")
data_XVSeq <- data_XVSeq[data_XVSeq$mutInfo != 2,]

data_scMut$tag <- paste(data_scMut$replicate, data_scMut$gene, data_scMut$cell, sep = "_")

# benchmarking steps
sample_stages <- c("Dx", "Rel")

candidate_genes <- c("ACAP2", "CWF19L2", "HNRNPUL1", "RPS24", "SMARCD1", "TET2_H1380Y", "TET2_Q1034", "TET2_R1216", "TET2_S792")

col_names <- c("tag", "XVseq", "scMut", "Common", "Precision", "Recall", "F1score")

result_benchmarking <- as.data.frame(matrix(data = 0, nrow = length(sample_stages) * length(candidate_genes), ncol = length(col_names)))
colnames(result_benchmarking) <- col_names

rowNum = 0

for (stage in sample_stages){
  xvseq_stage <- data_XVSeq[data_XVSeq$stage == stage & data_XVSeq$mutInfo_XVseq == 1,]
  scMut_stage <- data_scMut[data_scMut$stage == stage & data_scMut$mutInfo_scMut == 1,]
  for (gene in candidate_genes){
    rowNum <- rowNum + 1
    xvseq_stage_gene <- xvseq_stage[xvseq_stage$gene == gene,]
    scMut_stage_gene <- scMut_stage[scMut_stage$gene == gene,]
    tag <- paste(stage, gene, sep = "_")
    result_benchmarking[rowNum,]$tag <- tag
    result_benchmarking[rowNum, ]$XVseq <- nrow(xvseq_stage_gene)
    result_benchmarking[rowNum, ]$scMut <- nrow(scMut_stage_gene)
    result_benchmarking[rowNum, ]$Common <- length(intersect(xvseq_stage_gene$tag, scMut_stage_gene$tag))
    result_benchmarking[rowNum, ]$Precision <- result_benchmarking[rowNum, ]$Common / result_benchmarking[rowNum, ]$scMut
    result_benchmarking[rowNum, ]$Recall <- result_benchmarking[rowNum, ]$Common / result_benchmarking[rowNum, ]$XVseq
    result_benchmarking[rowNum, ]$F1score <- 2/((1/result_benchmarking[rowNum, ]$Precision) + (1/result_benchmarking[rowNum, ]$Recall))
  }
}

result_benchmarking$Precision[is.nan(result_benchmarking$Precision)] <- 0
result_benchmarking$Recall[is.nan(result_benchmarking$Recall)] <- 0
result_benchmarking$F1score[is.nan(result_benchmarking$F1score)] <- 0

rm(xvseq_stage)
rm(scMut_stage)
rm(xvseq_stage_gene)
rm(scMut_stage_gene)
```

# Plot benchmarking results
```{r plotBenchmarking}
selected_tags <- c("Dx_ACAP2", "Rel_ACAP2", "Dx_CWF19L2", "Rel_CWF19L2", "Dx_HNRNPUL1", "Rel_HNRNPUL1",
                   "Dx_TET2_H1380Y", "Rel_TET2_H1380Y", "Dx_TET2_Q1034", "Rel_TET2_Q1034",
                   "Dx_TET2_R1216", "Rel_TET2_R1216", "Dx_TET2_S792", "Rel_TET2_S792")

genesColor <- c(Dx_ACAP2 = "#a6cee3", Rel_ACAP2 = "#1f78b4",
                Dx_CWF19L2 = "#b2df8a", Rel_CWF19L2 = "#33a02c",
                Dx_HNRNPUL1 = "#fb9a99", Rel_HNRNPUL1 = "#e31a1c",
                Dx_RPS24 = "#fdbf6f", Rel_RPS24 = "#ff7f00",
                Dx_SMARCD1 = "#cab2d6", Rel_SMARCD1 = "#6a3d9a",
                Dx_TET2_H1380Y = "#ffffbf", Rel_TET2_H1380Y = "#ffff99",
                Dx_TET2_Q1034 = "#f6e8c3", Rel_TET2_Q1034 = "#b15928",
                Dx_TET2_R1216 = "#e6f598", Rel_TET2_R1216 = "#66c2a5",
                Dx_TET2_S792 = "#e0e0e0", Rel_TET2_S792 = "#878787")

result_benchmarking <- result_benchmarking[result_benchmarking$F1score > 0,]

p_benchmarking <- ggplot(data = result_benchmarking) + 
  geom_point(
    mapping = aes(x = Recall, y = Precision, fill = tag),
    color = "black",
    shape = 21, 
    size = 5, 
    alpha = 0.6,
    show.legend = TRUE
  ) +
  scale_fill_manual(values = genesColor) +  # scale_fill_manual
  xlab("Recall") + ylab("Precision") + 
  xlim(0, 0.6) +
  ylim(0, 1) +
  theme_classic() + 
  theme(
    axis.title = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.text.x = element_text(size = 20),
    legend.text = element_text(size = 15)
  )

p_benchmarking


venn_list_SMARCD1 <- list(scMut = unique(data_scMut %>% filter(mutInfo_scMut == 1 & gene == "SMARCD1") %>% pull(tag)), 
                            scXV  = unique(data_XVSeq %>% filter(mutInfo_XVseq == 1 & gene == "SMARCD1") %>% pull(tag)))

p_venn_SMARCD1 <- ggVennDiagram(venn_list_SMARCD1, category.names = c("scMut", "scXVSeq")) + scale_fill_distiller(palette = "RdBu")
p_venn_SMARCD1
```
# Proportion
```{r proportion}
col_result_proportion <- c("tag", "XVseqDxMut", "XVseqDxTotal", "XVseqReMut", "XVseqReTotal", "scMutDxMut", "scMutDxTotal", "scMutReMut", "scMutReTotal", "XVseqDx", "XVseqRe", "scMutraceDx", "scMutraceRe")

result_proportion <- as.data.frame(matrix(nrow = length(candidate_genes), ncol = length(col_result_proportion)))
colnames(result_proportion) <- col_result_proportion

rowNum <- 0
for (gene in candidate_genes){
  rowNum <- rowNum + 1
  tagTmp = gene
  result_proportion[rowNum,]$tag <- tagTmp
  result_proportion[rowNum,]$XVseqDxMut <- length(grep(tagTmp, data_XVSeq[data_XVSeq$mutInfo_XVseq == 1 & data_XVSeq$stage == "Dx",]$tag))
  result_proportion[rowNum,]$XVseqDxTotal <- length(grep(tagTmp, data_XVSeq[data_XVSeq$stage == "Dx",]$tag))
  result_proportion[rowNum,]$XVseqReMut <- length(grep(tagTmp, data_XVSeq[data_XVSeq$mutInfo_XVseq == 1 & data_XVSeq$stage == "Rel",]$tag))
  result_proportion[rowNum,]$XVseqReTotal <- length(grep(tagTmp, data_XVSeq[data_XVSeq$stage == "Rel",]$tag))
  
  result_proportion[rowNum,]$scMutDxMut <- length(grep(tagTmp, data_scMut[data_scMut$mutInfo_scMut == 1 & data_scMut$stage == "Dx",]$tag))
  result_proportion[rowNum,]$scMutDxTotal <- length(grep(tagTmp, data_scMut[data_scMut$stage == "Dx",]$tag))
  result_proportion[rowNum,]$scMutReMut <- length(grep(tagTmp, data_scMut[data_scMut$mutInfo_scMut == 1 & data_scMut$stage == "Rel",]$tag))
  result_proportion[rowNum,]$scMutReTotal <- length(grep(tagTmp, data_scMut[data_scMut$stage == "Rel",]$tag))
  
  result_proportion[rowNum,]$XVseqDx <- result_proportion[rowNum,]$XVseqDxMut / result_proportion[rowNum,]$XVseqDxTotal
  result_proportion[rowNum,]$XVseqRe <- result_proportion[rowNum,]$XVseqReMut / result_proportion[rowNum,]$XVseqReTotal
  result_proportion[rowNum,]$scMutraceDx <- result_proportion[rowNum,]$scMutDxMut / result_proportion[rowNum,]$scMutDxTotal
  result_proportion[rowNum,]$scMutraceRe <- result_proportion[rowNum,]$scMutReMut / result_proportion[rowNum,]$scMutReTotal
}

rownames(result_proportion) <- result_proportion$tag

result_proportion$XVseqDx[is.nan(result_proportion$XVseqDx)] <- 0
result_proportion$XVseqRe[is.nan(result_proportion$XVseqRe)] <- 0
result_proportion$scMutraceDx[is.nan(result_proportion$scMutraceDx)] <- 0
result_proportion$scMutraceRe[is.nan(result_proportion$scMutraceRe)] <- 0

max_val <- max(result_proportion[, c("XVseqDx", "XVseqRe", "scMutraceDx", "scMutraceRe")])

col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))

col_fun_v2 <- function(x) {
  ifelse(x == 0, "#404040", "#ca0020")
}

p_proportion <- Heatmap(
  as.matrix(result_proportion[, c("XVseqDx", "XVseqRe", "scMutraceDx", "scMutraceRe")]),
  name = "Proportion",
  col = col_fun_v2,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  row_names_side = "left",
  column_names_side = "top",
  cell_fun = function(j, i, x, y, width, height, fill) {
    grid.text(sprintf("%.2f", as.matrix(result_proportion[, c("XVseqDx", "XVseqRe", "scMutraceDx", "scMutraceRe")])[i, j]), x, y, gp = gpar(fontsize = 10, col = "white"))
  },
  rect_gp = gpar(col = "white", lwd = 3)
)

p_proportion
```

# CelltypeLevel
```{r celltypeLevel}
# reshape
data_scMut$newTag <- paste(data_scMut$replicate, data_scMut$cell, sep = "_")
data_scMut_reshape <- reshape(data_scMut[, c("newTag", "mutInfo_scMut", "gene")], idvar = "newTag", timevar = "gene", direction = "wide")
data_scMut_reshape[is.na(data_scMut_reshape)] <- 2

data_XVSeq_raw$newTag <- paste(data_XVSeq_raw$replicate, data_XVSeq_raw$cell, sep = "_")
data_XVseq_scMut <- merge(data_XVSeq_raw, data_scMut_reshape, by = "newTag", all.x = TRUE)
data_XVseq_scMut[is.na(data_XVseq_scMut)] <- 2

# pDC is classified under Myeloid, but extracted separately for highlighting

assign_newCellType <- function(dataInput){
  dataInput_pDC <- dataInput[dataInput$CellType %in% c("pDC"),]
  dataInput_pDC$lineage <- "pDC"
  dataInput$lineage[dataInput$CellType %in% c("HSPC", "GMP")] <- "HSPC"
  dataInput$lineage[dataInput$CellType %in% c("EarlyEry", "LateEry")] <- "Ery"
  dataInput$lineage[dataInput$CellType %in% c("ProMono", "Mono", "ncMono", "cDC", "pDC")] <- "Myeloid"
  dataInput$lineage[dataInput$CellType %in% c("ProB", "PreB", "B", "Plasma")] <- "Bcells"
  dataInput$lineage[dataInput$CellType %in% c("CD4Naive", "CD4Memory", "CD8Naive", "CD8Memory", "CD8TermExh", "GammaDeltaLike")] <- "Tcells"
  dataInput$lineage[dataInput$CellType %in% c("NKT", "NK")] <- "NK"
  res <- rbind(dataInput, dataInput_pDC)
  return(res)
}

data_celltype <- data_XVSeq_raw[,c("CellType", "newTag")]
data_XVSeq$newTag <- paste(data_XVSeq$replicate, data_XVSeq$cell, sep = "_")

data_scMut_meta <- merge(data_scMut, data_celltype, by = "newTag")
data_XVseq_meta <- merge(data_XVSeq, data_celltype, by = "newTag")

data_scMut_meta_lineage <- assign_newCellType(data_scMut_meta)
data_XVseq_meta_lineage <- assign_newCellType(data_XVseq_meta)

data_scMut_meta_lineage$newGene <- paste(data_scMut_meta_lineage$gene, data_scMut_meta_lineage$stage, sep = "_")
data_XVseq_meta_lineage$newGene <- paste(data_XVseq_meta_lineage$gene, data_XVseq_meta_lineage$stage, sep = "_")

# scMut
data_scMut_geneCellType_total <-  data_scMut_meta_lineage %>% count(newGene, lineage, name = "Count_scMut_total")
data_scMut_geneCellType_total$tag <- "scMut_total"
data_scMut_geneCellType_total$id <- paste(data_scMut_geneCellType_total$newGene, data_scMut_geneCellType_total$lineage, sep = "-")

data_scMut_geneCellType_mut <-  data_scMut_meta_lineage[data_scMut_meta_lineage$mutInfo_scMut == 1,] %>% count(newGene, lineage, name = "Count_scMut_mut")
data_scMut_geneCellType_mut$tag <- "scMut_mut"
data_scMut_geneCellType_mut$id <- paste(data_scMut_geneCellType_mut$newGene, data_scMut_geneCellType_mut$lineage, sep = "-")

# XVseq
data_XVseq_geneCellType_total <-  data_XVseq_meta_lineage %>% count(newGene, lineage, name = "Count_XVseq_total")
data_XVseq_geneCellType_total$tag <- "Dx_XVseq_total"
data_XVseq_geneCellType_total$id <- paste(data_XVseq_geneCellType_total$newGene, data_XVseq_geneCellType_total$lineage, sep = "-")

data_XVseq_geneCellType_mut <-  data_XVseq_meta_lineage[data_XVseq_meta_lineage$mutInfo_XVseq == 1,] %>% count(newGene, lineage, name = "Count_XVseq_mut")
data_XVseq_geneCellType_mut$tag <- "Dx_XVseq_mut"
data_XVseq_geneCellType_mut$id <- paste(data_XVseq_geneCellType_mut$newGene, data_XVseq_geneCellType_mut$lineage, sep = "-")

table_list_wide <- list(
  data_scMut_geneCellType_total[,c(3,5)], 
  data_scMut_geneCellType_mut[,c(3,5)],
  data_XVseq_geneCellType_total[,c(3,5)],
  data_XVseq_geneCellType_mut[,c(3,5)]
)

data_celltype_mut_count_wide_raw <- Reduce(function(x, y) merge(x, y, by = "id", all = TRUE), table_list_wide)
data_celltype_mut_count_wide_raw[is.na(data_celltype_mut_count_wide_raw)] <- 0

data_celltype_mut_count_wide <- separate(data_celltype_mut_count_wide_raw, col = "id", into = c("Gene", "lineage"), sep = "-")

data_celltype_mut_count_wide$freq_scMut <- data_celltype_mut_count_wide$Count_scMut_mut/data_celltype_mut_count_wide$Count_scMut_total
data_celltype_mut_count_wide$freq_XVSeq <- data_celltype_mut_count_wide$Count_XVseq_mut/data_celltype_mut_count_wide$Count_XVseq_total

data_celltype_mut_count_wide <- data_celltype_mut_count_wide %>%
  mutate(
    stage = ifelse(grepl("_Rel$", Gene), "Rel",
                   ifelse(grepl("_Dx$", Gene), "Dx", NA)),
    Gene_clean = sub("_(Rel|Dx)$", "", Gene)
  )

data_celltype_mut_count_wide$freq_scMut[is.nan(data_celltype_mut_count_wide$freq_scMut)] <- 0
data_celltype_mut_count_wide$freq_XVSeq[is.nan(data_celltype_mut_count_wide$freq_XVSeq)] <- 0

data_Dx_long <- data_celltype_mut_count_wide[data_celltype_mut_count_wide$stage == "Dx",]
setDT(data_Dx_long)
p_data_Dx_scMut <- dcast(
  data_Dx_long,
  Gene_clean ~ lineage,
  value.var = "freq_scMut"
) %>% 
  column_to_rownames("Gene_clean")
p_data_Dx_scMut[is.na(p_data_Dx_scMut)] <- 0

data_Rel_long <- data_celltype_mut_count_wide[data_celltype_mut_count_wide$stage == "Rel",]
setDT(data_Rel_long)
p_data_Re_scMut <- dcast(
  data_Rel_long,
  Gene_clean ~ lineage,
  value.var = "freq_scMut"
) %>% 
  column_to_rownames("Gene_clean")
p_data_Re_scMut[is.na(p_data_Re_scMut)] <- 0


p_data_Dx_XVseq <- dcast(
  data_Dx_long,
  Gene_clean ~ lineage,
  value.var = "freq_XVSeq"
) %>% 
  column_to_rownames("Gene_clean")

p_data_Dx_XVseq[is.na(p_data_Dx_XVseq)] <- 0

p_data_Re_XVseq <- dcast(
  data_Rel_long,
  Gene_clean ~ lineage,
  value.var = "freq_XVSeq"
) %>% 
  column_to_rownames("Gene_clean")
p_data_Re_XVseq[is.na(p_data_Re_XVseq)] <- 0

order_cellType <- c("pDC", "Myeloid", "HSPC", "Ery", "NK", "Bcells", "Tcells")
order_geneNames <- c("ACAP2", "CWF19L2", "HNRNPUL1", "RPS24", "SMARCD1", 
                     "TET2_H1380Y", "TET2_Q1034", "TET2_R1216", "TET2_S792")


max_val <- max(p_data_Dx_scMut)
col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))

p_proportion_Dx_scMut <- Heatmap(
  matrix = as.matrix(p_data_Dx_scMut[order_geneNames, order_cellType]),
  name = "Proportion",
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_heatmap_legend = FALSE,
  col = col_fun_v1,
  cell_fun = function(j, i, x, y, width, height, fill) {
    value <- as.matrix(p_data_Dx_scMut[order_geneNames, order_cellType])[i, j]
    grid.text(
      sprintf("%.2f", value),
      x, y,
      gp = gpar(fontsize = 10, col = "white")
    )
  },
  rect_gp = gpar(col = "white", lwd = 3)
)

max_val <- max(p_data_Re_scMut)
col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))

p_proportion_Re_scMut <- Heatmap(
  matrix = as.matrix(p_data_Re_scMut[order_geneNames, order_cellType]),
  name = "Proportion",
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_heatmap_legend = TRUE,
  col = col_fun_v1,
  cell_fun = function(j, i, x, y, width, height, fill) {
    value <- as.matrix(p_data_Re_scMut[order_geneNames, order_cellType])[i, j]
    grid.text(
      sprintf("%.2f", value),
      x, y,
      gp = gpar(fontsize = 10, col = "white")
    )
  },
  rect_gp = gpar(col = "white", lwd = 3)
)

max_val <- max(p_data_Dx_XVseq)
col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))

p_proportion_Dx_XVseq <- Heatmap(
  matrix = as.matrix(p_data_Dx_XVseq[order_geneNames, order_cellType]),
  name = "Proportion",
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_heatmap_legend = FALSE,
  col = col_fun_v1,
  cell_fun = function(j, i, x, y, width, height, fill) {
    value <- as.matrix(p_data_Dx_XVseq[order_geneNames, order_cellType])[i, j]
    grid.text(
      sprintf("%.2f", value),
      x, y,
      gp = gpar(fontsize = 10, col = "white")
    )
  },
  rect_gp = gpar(col = "white", lwd = 3)
)

max_val <- max(p_data_Re_XVseq)
col_fun_v1 <- colorRamp2(c(0, max_val * 0.33, max_val * 0.66, max_val), c("#404040", "#bababa", "#f4a582", "#ca0020"))
p_proportion_Re_XVseq <- Heatmap(
  matrix = as.matrix(p_data_Re_XVseq[order_geneNames, order_cellType]),
  name = "Proportion",
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_heatmap_legend = FALSE,
  col = col_fun_v1,
  cell_fun = function(j, i, x, y, width, height, fill) {
    value <- as.matrix(p_data_Re_XVseq[order_geneNames, order_cellType])[i, j]
    grid.text(
      sprintf("%.2f", value),
      x, y,
      gp = gpar(fontsize = 10, col = "white")
    )
  },
  rect_gp = gpar(col = "white", lwd = 3)
)

p_merge_proportion_celltype <- p_proportion_Dx_XVseq + p_proportion_Re_XVseq + p_proportion_Dx_scMut + p_proportion_Re_scMut

p_merge_proportion_celltype
```

# UMAPLevel celltype annotation
```{r UMAPLevel}
colorCelltype_1 <- c(HSPC = "#000000", EarlyEry = "#FF9338", LateEry = "#80C578", GMP = "#9F9F9F", ProMono = "#804B17",
                   Mono = "#FFEE34", ncMono = "#2BD1D3", cDC = "#1C6814", pDC = "#AF2325", ProB = "#8227C1",
                   PreB = "#9EB1FF", B = "#2B4ADE", Plasma = "#575757", CD4Naive = "#7F7F05", CD4Memory = "#FECEEF",
                   CD8Naive = "#FFD702", CD8Memory = "#E4E0BD", CD8TermExh = "#8E4817", GammaDeltaLike = "#727F8C",
                   NKT = "#F0837E", NK = "#BB8B66")

colorCelltype_2 <- c(HSPC = "#d9d9d9", EarlyEry = "#d9d9d9", LateEry = "#d9d9d9", GMP = "#d9d9d9", ProMono = "#d9d9d9",
                   Mono = "#d9d9d9", ncMono = "#d9d9d9", cDC = "#d9d9d9", pDC = "#AF2325", ProB = "#d9d9d9",
                   PreB = "#d9d9d9", B = "#d9d9d9", Plasma = "#d9d9d9", CD4Naive = "#d9d9d9", CD4Memory = "#d9d9d9",
                   CD8Naive = "#d9d9d9", CD8Memory = "#d9d9d9", CD8TermExh = "#d9d9d9", GammaDeltaLike = "#d9d9d9",
                   NKT = "#d9d9d9", NK = "#d9d9d9")

colorCelltype_3 <- c(pDC = "#AF2325", Myeloid = "#fb6a4a", HSPC = "#000000", Ery = "#FF9338", NK = "#BB8B66", Bcells = "#2B4ADE", Tcells = "#727F8C")

colorCelltype_4 <- c(Malignant = "#8227C1", Other = "#d9d9d9", Premalignant = "#969696")


data_XVSeq_raw_new <- assign_newCellType(data_XVSeq_raw)

# all sub celltypes
p_Dx_celltype <- ggplot(data = data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Dx",]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = CellType), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_1) +
  xlab("") + ylab("") +
  theme_classic()

p_Re_celltype <- ggplot(data = data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Rel",]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = CellType), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_1) +
  xlab("") + ylab("") +
  theme_classic()

# highlight pDC
p_Dx_celltype_2 <- ggplot(data = data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Dx",]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = CellType), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_2) +
  xlab("") + ylab("") +
  theme_classic()

p_Re_celltype_2 <- ggplot(data = data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Rel",]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = CellType), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_2) +
  xlab("") + ylab("") +
  theme_classic()

# main celltypes
p_Dx_celltype_3 <- ggplot(data = data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Dx",]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = lineage), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_3) +
  xlab("") + ylab("") +
  theme_classic()

p_Re_celltype_3 <- ggplot(data = data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Rel",]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = lineage), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_3) +
  xlab("") + ylab("") +
  theme_classic()

# merge stage
p_celltype_4 <- ggplot(data = data_XVSeq_raw_new[,c("project_umap_x", "project_umap_y", "lineage", "is_malignant")]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = lineage), size = 1.5, show.legend = TRUE) +
  scale_color_manual(values = colorCelltype_3) +
  xlab("") + ylab("") +
  theme_classic()

# is_malignant
p_celltype_5 <- ggplot(data = data_XVSeq_raw_new[,c("project_umap_x", "project_umap_y", "lineage", "is_malignant")]) + geom_point(mapping =  aes(x = project_umap_x, y = project_umap_y, color = is_malignant), size = 1.5, show.legend = FALSE) +
  scale_color_manual(values = colorCelltype_4) +
  xlab("") + ylab("") +
  theme_classic()

p_Dx_celltype
p_Re_celltype

p_Dx_celltype_2
p_Re_celltype_2

p_Dx_celltype_3
p_Re_celltype_3

p_celltype_4
p_celltype_5
```

# UMAPLevel mutation
```{r UMAPMutation}
# scMut
data_umap <- data_XVSeq_raw_new[,c("newTag", "project_umap_x", "project_umap_y")]
data_scMut_meta_umap <- merge(data_scMut_meta, data_umap, by = "newTag")


plot_mutation_distribution_scMut <- function(data_XVSeq_raw_new, stage_param, data_scMut_meta_umap, gene_param){
  
  data_tmp <- data_XVSeq_raw_new %>%
    filter(stage %in% stage_param)
  
  data_mut <- data_scMut_meta_umap %>%
    filter(stage %in% stage_param, gene %in% gene_param, mutInfo_scMut == 1)
  
  ggplot(data = data_tmp) + 
    geom_point(aes(x = project_umap_x, y = project_umap_y), 
               color = "#d9d9d9", size = 1.5) +
    geom_point(data = data_mut, aes(x = project_umap_x, y = project_umap_y), 
               color = "#ca0020", alpha = 0.5, size = 1.5) +
    xlab("") + ylab("") + theme_classic()
}

order_geneNames <- c("ACAP2", "CWF19L2", "HNRNPUL1", "RPS24", "SMARCD1", "TET2_H1380Y", "TET2_Q1034", "TET2_R1216", "TET2_S792")

p_Dx_ACAP2_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "ACAP2")
p_Re_ACAP2_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "ACAP2")
p_Dx_CWF19L2_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "CWF19L2")
p_Re_CWF19L2_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "CWF19L2")
p_Dx_HNRNPUL1_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "HNRNPUL1")
p_Re_HNRNPUL1_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "HNRNPUL1")
p_Dx_RPS24_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "RPS24")
p_Re_RPS24_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "RPS24")
p_Dx_SMARCD1_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "SMARCD1")
p_Re_SMARCD1_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "SMARCD1")
p_Dx_TET2_H1380Y_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "TET2_H1380Y")
p_Re_TET2_H1380Y_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "TET2_H1380Y")
p_Dx_TET2_Q1034_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "TET2_Q1034")
p_Re_TET2_Q1034_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "TET2_Q1034")
p_Dx_TET2_R1216_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "TET2_R1216")
p_Re_TET2_R1216_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "TET2_R1216")
p_Dx_TET2_S792_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, "TET2_S792")
p_Re_TET2_S792_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, "TET2_S792")

p_Dx_allgene_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Dx", data_scMut_meta_umap, order_geneNames)
p_Re_allgene_scMut <- plot_mutation_distribution_scMut(data_XVSeq_raw_new, "Rel", data_scMut_meta_umap, order_geneNames)


p_Dx_ACAP2_scMut
p_Re_ACAP2_scMut
p_Dx_CWF19L2_scMut
p_Re_CWF19L2_scMut
p_Dx_HNRNPUL1_scMut
p_Re_HNRNPUL1_scMut
p_Dx_RPS24_scMut
p_Re_RPS24_scMut
p_Dx_SMARCD1_scMut
p_Re_SMARCD1_scMut
p_Dx_TET2_H1380Y_scMut
p_Re_TET2_H1380Y_scMut
p_Dx_TET2_Q1034_scMut
p_Re_TET2_Q1034_scMut
p_Dx_TET2_R1216_scMut
p_Re_TET2_R1216_scMut
p_Dx_TET2_S792_scMut
p_Re_TET2_S792_scMut

p_Dx_allgene_scMut
p_Re_allgene_scMut


plot_mutation_distribution_XVSeq <- function(data_XVSeq_raw_new, stage_param, data_XVSeq_meta_umap, gene_param){
  
  data_tmp <- data_XVSeq_raw_new %>%
    filter(stage %in% stage_param)
  
  data_mut <- data_XVSeq_meta_umap %>%
    filter(stage %in% stage_param, gene %in% gene_param, mutInfo_XVseq == 1)
  
  ggplot(data = data_tmp) + 
    geom_point(aes(x = project_umap_x, y = project_umap_y), 
               color = "#d9d9d9", size = 1.5) +
    geom_point(data = data_mut, aes(x = project_umap_x, y = project_umap_y), 
               color = "#ca0020", alpha = 0.5, size = 1.5) +
    xlab("") + ylab("") + theme_classic()
}

# XVSeq
data_XVSeq_meta_umap <- merge(data_XVseq_meta, data_umap, by = "newTag")

p_Dx_ACAP2_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "ACAP2")
p_Re_ACAP2_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "ACAP2")

p_Dx_CWF19L2_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "CWF19L2")
p_Re_CWF19L2_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "CWF19L2")

p_Dx_HNRNPUL1_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "HNRNPUL1")
p_Re_HNRNPUL1_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "HNRNPUL1")

p_Dx_RPS24_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "RPS24")
p_Re_RPS24_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "RPS24")

p_Dx_SMARCD1_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "SMARCD1")
p_Re_SMARCD1_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "SMARCD1")

p_Dx_TET2_H1380Y_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "TET2_H1380Y")
p_Re_TET2_H1380Y_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "TET2_H1380Y")

p_Dx_TET2_Q1034_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "TET2_Q1034")
p_Re_TET2_Q1034_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "TET2_Q1034")

p_Dx_TET2_R1216_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "TET2_R1216")
p_Re_TET2_R1216_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "TET2_R1216")

p_Dx_TET2_S792_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, "TET2_S792")
p_Re_TET2_S792_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, "TET2_S792")

p_Dx_allgene_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Dx", data_XVSeq_meta_umap, order_geneNames)
p_Re_allgene_XVSeq <- plot_mutation_distribution_XVSeq(data_XVSeq_raw_new, "Rel", data_XVSeq_meta_umap, order_geneNames)

p_Dx_ACAP2_XVSeq
p_Re_ACAP2_XVSeq
p_Dx_CWF19L2_XVSeq
p_Re_CWF19L2_XVSeq
p_Dx_HNRNPUL1_XVSeq
p_Re_HNRNPUL1_XVSeq
p_Dx_RPS24_XVSeq
p_Re_RPS24_XVSeq
p_Dx_SMARCD1_XVSeq
p_Re_SMARCD1_XVSeq
p_Dx_TET2_H1380Y_XVSeq
p_Re_TET2_H1380Y_XVSeq
p_Dx_TET2_Q1034_XVSeq
p_Re_TET2_Q1034_XVSeq
p_Dx_TET2_R1216_XVSeq
p_Re_TET2_R1216_XVSeq
p_Dx_TET2_S792_XVSeq
p_Re_TET2_S792_XVSeq
p_Dx_allgene_XVSeq
p_Re_allgene_XVSeq
```


# PropotionMutCells
```{r countPropotionMutCells}
order_geneNames <- c("ACAP2", "CWF19L2", "HNRNPUL1", "RPS24", "SMARCD1", "TET2_H1380Y", "TET2_Q1034", "TET2_R1216", "TET2_S792")

# XVSeq
data_XVSeq_raw_new_DX <- data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Dx",]
data_XVSeq_raw_new_RE <- data_XVSeq_raw_new[data_XVSeq_raw_new$stage == "Rel",]

data_XVSeq_raw_new_DX <- data_XVSeq_raw_new_DX %>%
  mutate(is_XVseq_Dx_mut = ACAP2 == 1 | CWF19L2 == 1 | HNRNPUL1 == 1 | RPS24 == 1 | SMARCD1 == 1 | TET2_H1380Y == 1 | TET2_Q1034 == 1 | TET2_S792 == 1 | TET2_R1216 == 1)

data_XVSeq_raw_new_RE <- data_XVSeq_raw_new_RE %>%
  mutate(is_XVseq_Dx_mut = ACAP2 == 1 | CWF19L2 == 1 | HNRNPUL1 == 1 | RPS24 == 1 | SMARCD1 == 1 | TET2_H1380Y == 1 | TET2_Q1034 == 1 | TET2_S792 == 1 | TET2_R1216 == 1)

# DX XVSeq
num_XVSeq_Dx_Malignant_mut <- length(data_XVSeq_raw_new_DX[data_XVSeq_raw_new_DX$is_malignant == "Malignant" & data_XVSeq_raw_new_DX$is_XVseq_Dx_mut == "TRUE",]$newTag)
num_XVSeq_Dx_Malignant_wt <- length(data_XVSeq_raw_new_DX[data_XVSeq_raw_new_DX$is_malignant == "Malignant" & data_XVSeq_raw_new_DX$is_XVseq_Dx_mut == "FALSE",]$newTag)

num_XVSeq_Dx_NotMalignant_mut <- length(data_XVSeq_raw_new_DX[data_XVSeq_raw_new_DX$is_malignant != "Malignant" & data_XVSeq_raw_new_DX$is_XVseq_Dx_mut == "TRUE",]$newTag)
num_XVSeq_Dx_NotMalignant_wt <- length(data_XVSeq_raw_new_DX[data_XVSeq_raw_new_DX$is_malignant != "Malignant" & data_XVSeq_raw_new_DX$is_XVseq_Dx_mut == "FALSE",]$newTag)

data_propotionMutCells_XVSeq_Dx <- matrix(c(num_XVSeq_Dx_Malignant_mut, num_XVSeq_Dx_Malignant_wt, num_XVSeq_Dx_NotMalignant_mut, num_XVSeq_Dx_NotMalignant_wt),nrow = 2, byrow = T, dimnames = list(group = c("Malignant","Benign"), effect = c("Mut","WT")))

chisq.test(data_propotionMutCells_XVSeq_Dx,correct = T)
fisher.test(data_propotionMutCells_XVSeq_Dx)

data_propotionMutCells_XVSeq_Dx_long <- reshape2::melt(data_propotionMutCells_XVSeq_Dx, id.vars = "Group", variable.name = "MutType", value.name = "Count")
ggplot(data_propotionMutCells_XVSeq_Dx_long, aes(x = group, y = Count, fill = effect)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("#ca0020", "#d9d9d9")) +
  theme_classic()


# RE XVSeq
num_XVSeq_Re_Malignant_mut <- length(data_XVSeq_raw_new_RE[data_XVSeq_raw_new_RE$is_malignant == "Malignant" & data_XVSeq_raw_new_RE$is_XVseq_Dx_mut == "TRUE",]$newTag)
num_XVSeq_Re_Malignant_wt <- length(data_XVSeq_raw_new_RE[data_XVSeq_raw_new_RE$is_malignant == "Malignant" & data_XVSeq_raw_new_RE$is_XVseq_Dx_mut == "FALSE",]$newTag)

num_XVSeq_Re_NotMalignant_mut <- length(data_XVSeq_raw_new_RE[data_XVSeq_raw_new_RE$is_malignant != "Malignant" & data_XVSeq_raw_new_RE$is_XVseq_Dx_mut == "TRUE",]$newTag)
num_XVSeq_Re_NotMalignant_wt <- length(data_XVSeq_raw_new_RE[data_XVSeq_raw_new_RE$is_malignant != "Malignant" & data_XVSeq_raw_new_RE$is_XVseq_Dx_mut == "FALSE",]$newTag)

data_propotionMutCells_XVSeq_Re <- matrix(c(num_XVSeq_Re_Malignant_mut, num_XVSeq_Re_Malignant_wt, num_XVSeq_Re_NotMalignant_mut, num_XVSeq_Re_NotMalignant_wt),nrow = 2, byrow = T, dimnames = list(group = c("Malignant","Benign"), effect = c("Mut","WT")))

chisq.test(data_propotionMutCells_XVSeq_Re,correct = T)
fisher.test(data_propotionMutCells_XVSeq_Re)

data_propotionMutCells_XVSeq_Re_long <- reshape2::melt(data_propotionMutCells_XVSeq_Re, id.vars = "Group", variable.name = "MutType", value.name = "Count")
ggplot(data_propotionMutCells_XVSeq_Re_long, aes(x = group, y = Count, fill = effect)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("#ca0020", "#d9d9d9")) +
  theme_classic()

# scMut
data_scMut_raw_new_DX <- data_XVseq_scMut[data_XVseq_scMut$stage == "Dx",]
data_scMut_raw_new_RE <- data_XVseq_scMut[data_XVseq_scMut$stage == "Rel",]

data_scMut_raw_new_DX <- data_scMut_raw_new_DX %>%
  mutate(is_scMut_Dx_mut = mutInfo_scMut.ACAP2 == 1 | mutInfo_scMut.CWF19L2 == 1 | mutInfo_scMut.HNRNPUL1 == 1 | mutInfo_scMut.RPS24 == 1 | mutInfo_scMut.SMARCD1 == 1 | mutInfo_scMut.TET2_H1380Y == 1 | mutInfo_scMut.TET2_Q1034 == 1 | mutInfo_scMut.TET2_R1216 == 1 | mutInfo_scMut.TET2_S792 == 1)

data_scMut_raw_new_RE <- data_scMut_raw_new_RE %>%
  mutate(is_scMut_Re_mut = mutInfo_scMut.ACAP2 == 1 | mutInfo_scMut.CWF19L2 == 1 | mutInfo_scMut.HNRNPUL1 == 1 | mutInfo_scMut.RPS24 == 1 | mutInfo_scMut.SMARCD1 == 1 | mutInfo_scMut.TET2_H1380Y == 1 | mutInfo_scMut.TET2_Q1034 == 1 | mutInfo_scMut.TET2_R1216 == 1 | mutInfo_scMut.TET2_S792 == 1)

# DX scMut
num_scMut_Dx_Malignant_mut <- length(data_scMut_raw_new_DX[data_scMut_raw_new_DX$is_malignant == "Malignant" & data_scMut_raw_new_DX$is_scMut_Dx_mut == "TRUE",]$newTag)
num_scMut_Dx_Malignant_wt <- length(data_scMut_raw_new_DX[data_scMut_raw_new_DX$is_malignant == "Malignant" & data_scMut_raw_new_DX$is_scMut_Dx_mut == "FALSE",]$newTag)

num_scMut_Dx_NotMalignant_mut <- length(data_scMut_raw_new_DX[data_scMut_raw_new_DX$is_malignant != "Malignant" & data_scMut_raw_new_DX$is_scMut_Dx_mut == "TRUE",]$newTag)
num_scMut_Dx_NotMalignant_wt <- length(data_scMut_raw_new_DX[data_scMut_raw_new_DX$is_malignant != "Malignant" & data_scMut_raw_new_DX$is_scMut_Dx_mut == "FALSE",]$newTag)

data_propotionMutCells_scMut_Dx <- matrix(c(num_scMut_Dx_Malignant_mut, num_scMut_Dx_Malignant_wt, num_scMut_Dx_NotMalignant_mut, num_scMut_Dx_NotMalignant_wt),nrow = 2, byrow = T, dimnames = list(group = c("Malignant","Benign"), effect = c("Mut","WT")))

chisq.test(data_propotionMutCells_scMut_Dx,correct = T)
fisher.test(data_propotionMutCells_scMut_Dx)

data_propotionMutCells_scMut_Dx_long <- reshape2::melt(data_propotionMutCells_scMut_Dx, id.vars = "Group", variable.name = "MutType", value.name = "Count")
ggplot(data_propotionMutCells_scMut_Dx_long, aes(x = group, y = Count, fill = effect)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("#ca0020", "#d9d9d9")) +
  theme_classic()


# RE scMut
num_scMut_Re_Malignant_mut <- length(data_scMut_raw_new_RE[data_scMut_raw_new_RE$is_malignant == "Malignant" & data_scMut_raw_new_RE$is_scMut_Re_mut == "TRUE",]$newTag)
num_scMut_Re_Malignant_wt <- length(data_scMut_raw_new_RE[data_scMut_raw_new_RE$is_malignant == "Malignant" & data_scMut_raw_new_RE$is_scMut_Re_mut == "FALSE",]$newTag)

num_scMut_Re_NotMalignant_mut <- length(data_scMut_raw_new_RE[data_scMut_raw_new_RE$is_malignant != "Malignant" & data_scMut_raw_new_RE$is_scMut_Re_mut == "TRUE",]$newTag)
num_scMut_Re_NotMalignant_wt <- length(data_scMut_raw_new_RE[data_scMut_raw_new_RE$is_malignant != "Malignant" & data_scMut_raw_new_RE$is_scMut_Re_mut == "FALSE",]$newTag)

data_propotionMutCells_scMut_Re <- matrix(c(num_scMut_Re_Malignant_mut, num_scMut_Re_Malignant_wt, num_scMut_Re_NotMalignant_mut, num_scMut_Re_NotMalignant_wt),nrow = 2, byrow = T, dimnames = list(group = c("Malignant","Benign"), effect = c("Mut","WT")))

chisq.test(data_propotionMutCells_scMut_Re,correct = T)
fisher.test(data_propotionMutCells_scMut_Re)

data_propotionMutCells_scMut_Re_long <- reshape2::melt(data_propotionMutCells_scMut_Re, id.vars = "Group", variable.name = "MutType", value.name = "Count")
ggplot(data_propotionMutCells_scMut_Re_long, aes(x = group, y = Count, fill = effect)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("#ca0020", "#d9d9d9")) +
  theme_classic()
```

# SessionInfo
```{r sessionInfo}
sessionInfo()
```
