---
title: "Figure 3"
author: "Qun Li"
date: "13 Aug 2025 at 14:07:57"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
  html_document:
    toc: true
    toc_depth: '3'
    df_print: paged
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

#ENV
```{r envs}
rm(list = ls())
setwd("/Users/liqun/Desktop/scMutrace-tutorial/ReproducibilityAnalysis/Figure3/")
```

# Libraries
```{r libraries}
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(dplyr)
library(tidyr)
library(ComplexHeatmap)
library(circlize)
```


# Load Data
```{r loadData}
# XVSeq
# Ultraviolet radiation shapes dendritic cell leukaemia transformation in the skin
# https://www.nature.com/articles/s41586-023-06156-8
# Mutation_sample_XVSeq  <- read.csv("../Data/XVSeq/Mutation_sample.csv", row.names = 1)
# Mutation_sample_XVSeq[is.na(Mutation_sample_XVSeq)] <- 0
# Mutation_sample_XVSeq$Gene <- rownames(Mutation_sample_XVSeq)

# GoTSeq
# Deconvoluting clonal and cellular architecture in IDH-mutant acute myeloid leukemia
# https://www.cell.com/cell-stem-cell/fulltext/S1934-5909(25)00179-1
# Mutation_sample_GoTSeq <- read.csv("../Data/GoT/Mutation_sample.csv", row.names = 1)
# Mutation_sample_GoTSeq[is.na(Mutation_sample_GoTSeq)] <- 0
# Mutation_sample_GoTSeq$Gene <- rownames(Mutation_sample_GoTSeq)

# SMARTSeq
# Therapy-Induced Evolution of Human Lung Cancer Revealed by Single-Cell RNA Sequencing
# https://www.sciencedirect.com/science/article/pii/S0092867420308825
# Mutation_sample_SMARTSeq <- read.csv("../Data/SMARTSeq/Mutation_sample.csv", row.names = 1)
# Mutation_sample_SMARTSeq[is.na(Mutation_sample_SMARTSeq)] <- 0
# Mutation_sample_SMARTSeq$Gene <- rownames(Mutation_sample_SMARTSeq)

# Merge
# Mutation_sample_XVSeq  <- Mutation_sample_XVSeq  |> dplyr::rename_with(~ paste0("XVSeq_", .), -Gene)
# Mutation_sample_GoTSeq <- Mutation_sample_GoTSeq |> dplyr::rename_with(~ paste0("GoTSeq_", .), -Gene)
# Mutation_sample_SMARTSeq <- Mutation_sample_SMARTSeq |> dplyr::rename_with(~ paste0("SMARTSeq_", .), -Gene)

# Merged_mutation <- Mutation_sample_XVSeq %>%
#   dplyr::full_join(Mutation_sample_GoTSeq, by = "Gene") %>%
#   dplyr::full_join(Mutation_sample_SMARTSeq, by = "Gene")

# Merged_mutation[is.na(Merged_mutation)] <- 0

# save merge data
# write.csv(Merged_mutation, "../Data/0_Mutation_sample_merge.csv")

# load Mutation sample matrix
Merged_mutation <- read.csv("../Data/MergeData/0_Mutation_sample_merge.csv")

# load Mutant cell fraction
Mutation_fraction <- read.csv("../Data/MergeData/0_Benchmarking_MutCellFrac.csv", header = T)

rownames(Merged_mutation) <- Merged_mutation$Gene
Merged_mutation_Ann <- Merged_mutation[, c("Gene", "Tag")]
Merged_mutation$Gene <- NULL
Merged_mutation$Tag <- NULL

# heatmap
mat <- as.matrix(Merged_mutation)
bin_mat <- ifelse(mat > 0, 1, 0)

col_fun2 <- c("0" = "#202020",
              "1" = "#ca0020")

Heatmap(
  t(bin_mat),
  name = "Mutation",
  col = col_fun2,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  row_names_side = "left",
  column_names_side = "top",
  rect_gp = gpar(col = "white", lwd = 1)
)


p_correlation_scMut_OtherMethods <- ggplot(Mutation_fraction, aes(x = scMutrace, y = OtherMethod)) +
  geom_point(size = 1.5, color = "#202020") +
  geom_smooth(method = "lm", se = TRUE, color = "#ca0020", linetype = "dashed", lwd = 1.2) +
  theme_classic(base_size = 16) +
  xlab("scMutrace") +
  ylab("OtherMethod") +
  xlim(0, 1) + ylim(0, 0.6) +
  annotate("text",
           x = max(Mutation_fraction$scMutrace) * 0.7,
           y = max(Mutation_fraction$OtherMethod) * 0.15,
           label = paste0("r = ", round(cor(Mutation_fraction$scMutrace, Mutation_fraction$OtherMethod), 3)),
           size = 5)

cor.test(Mutation_fraction$scMutrace, Mutation_fraction$OtherMethod, method = "pearson")

p_correlation_scMut_OtherMethods

# clean mat
rm(mat, bin_mat)
```

# benchmarking
```{r lmFracMutCells}
benchmarking_data <- read.csv("../Data/MergeData/0_Benchmarking_Data.csv", header = T)

p_benchmarking_res <- ggplot(data = benchmarking_data) + 
  geom_point(mapping = aes(x = Recall, y = Precision, fill = Tag),
    color = "black", shape = 21, size = 3, show.legend = TRUE) +
  scale_fill_manual(values = c("#1f78b4", "#e31a1c", "#33a02c")) +
  xlab("Recall") + ylab("Precision") + xlim(0, 1) + ylim(0, 1) +
  theme_classic() + 
  theme(
    axis.title = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.text.x = element_text(size = 20),
    legend.text = element_text(size = 15)
  )

p_benchmarking_res
```

# GO
```{r GO}
GO_mutation <- read.csv("../Data/MergeData/1_GO.csv", header = T)

p_GOs_mutation <- ggplot(GO_mutation, aes(x = reorder(Description, Count), y = Count, fill = Type)) +
  geom_bar(stat = "identity", width = 0.7) +
  coord_flip() +
  geom_text(aes(label = Count), hjust = -0.1, size = 4, color = "black") +
  labs(
    x = "GO Term",
    y = "Gene Count",
    title = "Top 10 (patient and healthy)"
  ) + theme_minimal() +
  theme(
    axis.text = element_text(size = 12, color = "black"),
    axis.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    legend.position = "none",
    panel.grid.major.y = element_blank()
  ) + ylim(0, max(GO_mutation$Count)*1.15) +
  scale_fill_manual(values = c(
    "AML" = "#d95f02",
    "CH" = "#1b9e77",
    "Healthy" = "#7570b3"))

p_GOs_mutation
```

# SBS mutation signatures
```{r SBS}
SBS_data <- read.csv("../Data/MergeData/Signature_contributions_PDC.csv", header = T)
df_long <- SBS_data %>%
  tidyr::pivot_longer(cols = c(DX, RE), 
               names_to = "Stage", 
               values_to = "Contribution")

signature_colors <- c(
  "SBS1" = "#a6cee3",
  "SBS5" = "#1f78b4",
  "SBS7a" = "#e31a1c", 
  "SBS7b" = "#fb9a99",
  "SBS37" = "#737373",
  "SBS44" = "#f0f0f0"
)

p_SBS_XVSeq <- ggplot(df_long, aes(x = Stage, y = Contribution, fill = Signature)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = signature_colors) +
  theme_bw() +
  labs(
    title = "Mutational Signature Contributions (DX vs RE)",
    x = "Stage",
    y = "Contribution"
  )

p_SBS_XVSeq
```

# sessionInfo
```{r sessionInfo}
sessionInfo()
```





