---
title: "accumulatedMutations_HSPC"
author: "Qun Li"
date: "21 Aug 2025 at 09:40:36"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
  word_document:
    toc: true
    toc_depth: '3'
  html_document:
    toc: true
    toc_depth: '3'
    df_print: paged
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Env
```{r envs}
rm(list = ls())
setwd("/Users/liqun/Desktop/scMutrace-tutorial/ReproducibilityAnalysis/Figure5/")
```

# Libraries
```{r libraries}
library(FSA)
library(ineq)
library(vegan)
library(dplyr)
library(tidyr)
library(ggpubr)
library(Seurat)
library(igraph)
library(ggraph)
library(webshot)
library(ggplot2)
library(ggpmisc)
library(stringr)
library(corrplot)
library(pheatmap)
library(reshape2)
library(tidygraph)
library(networkD3)
library(tidyverse)
library(patchwork)
```

# Functions
```{r function}
retriveCellsByLocation <- function(CSM, locList){
  CSM$CellTag <- rownames(CSM)
  CSM_tmp <- CSM[, c("CellTag",locList)]
  data_MutPerCell_CSM_tmp <- data.frame(
    CellTag = rownames(CSM_tmp),
    MutNum = rowSums(CSM_tmp == "Mut"),
    WTNum = rowSums(CSM_tmp == "WT")
  )
  cells_Total <- data_MutPerCell_CSM_tmp[rowSums(data_MutPerCell_CSM_tmp[,c("MutNum", "WTNum")]) > 0, ]$CellTag
  cells_WT <-    data_MutPerCell_CSM_tmp[data_MutPerCell_CSM_tmp[,"WTNum"] > 0,]$CellTag
  cells_Mut <-   data_MutPerCell_CSM_tmp[data_MutPerCell_CSM_tmp[,"MutNum"] > 0,]$CellTag
  cells <- list(Total = cells_Total, Mut = cells_Mut, WT = cells_WT)
  return(cells)
}

retriveLocsByCells <- function(CSM, cellList){
  CSM$CellTag <- rownames(CSM)
  CSM_tmp <- CSM[CSM$CellTag %in% cellList,]
  data_CellPerMut_CSM_tmp <- data.frame(
    Location = colnames(CSM_tmp),
    CellMutNum = colSums(CSM_tmp == "Mut"),
    CellWTNum = colSums(CSM_tmp == "WT")
  )
  pos_Total <- data_CellPerMut_CSM_tmp[rowSums(data_CellPerMut_CSM_tmp[, c("CellMutNum", "CellWTNum")]) > 0,]$Location
  pos_Mut <- data_CellPerMut_CSM_tmp[data_CellPerMut_CSM_tmp[, "CellMutNum"] > 0 ,]$Location
  pos_WT <- data_CellPerMut_CSM_tmp[data_CellPerMut_CSM_tmp[, "CellWTNum"] > 0 ,]$Location
  pos <- list(Total = pos_Total, Mut = pos_Mut, WT = pos_WT)
  return(pos)
}

cal_MultiSpe <- function(matrixData) {
  
  res <- data.frame(
    Shannon = vegan::diversity(matrixData, index = "shannon"),
    Simpson = vegan::diversity(matrixData, index = "simpson"),
    Gini = apply(matrixData, 1, function(x) ineq(x + 0.00001, type = "Gini")),
    sumMut = rowSums(matrixData),
    Tau = NA
  )
  
  # Tau = sum(1 - (x / max(x))) / (n - 1)
  res$Tau <- apply(matrixData, 1, function(x) {
    if (all(x == 0)) return(NA)
    x <- x / max(x)
    sum(1 - x) / (length(x) - 1)
  })
  
  rownames(res) <- rownames(matrixData)
  return(res)
}

scale01 <- function(x) (x - min(x)) / (max(x) - min(x))

cal_scMutScore <- function(data_cell_mut, data_mut_time, data_meta, coefficient_gini = 0.1){
  # data_cell_mut [cell * muts]
  # data_mut_time [muts * tissues/celltype/days]
  # data_meta [Cellbarcode, CellMutTag(tissues/celltype/days)]
  # data_cell_time_matrix
  replacement_map <- c("NoCall" = 0, "WT" = 0, "Mut" = 1)
  
  data_cell_mut_num <- as.data.frame(lapply(data_cell_mut, function(x) {
    ifelse(x %in% names(replacement_map), replacement_map[x], x)
  }))

  rownames(data_cell_mut_num) <- rownames(data_cell_mut)
  print(dim(data_cell_mut_num))
  print(dim(data_mut_time))
  
  data_cell_time_matrix <- as.matrix(data_cell_mut_num) %*% as.matrix(data_mut_time)
  rownames(data_cell_time_matrix) <- rownames(data_cell_mut)
  colnames(data_cell_time_matrix) <- colnames(data_mut_time)
  
  muts_total <- unique(rownames(data_mut_time))

  # get different tissues/time/celltype names
  col_names_data <- colnames(data_cell_time_matrix)
  
  col_lenghth <- length(col_names_data)
  
  col_coefficient_fix <- setNames(
    rep(1/col_lenghth, col_lenghth),
    col_names_data
  )

  data_cell_time_matrix <- data_cell_time_matrix[,col_names_data]
  
  # Gini
  res_index <- cal_MultiSpe(data_cell_time_matrix)
  
  res_diversity <- as.data.frame((data_cell_time_matrix > 1) * rep(col_coefficient_fix[colnames(data_cell_time_matrix)], each = nrow(data_cell_time_matrix)))
  res_diversity$Diversity <- rowSums(res_diversity)

  res_diversity$Diversity[is.na(res_diversity$Diversity)] <- 0.00001
  
  res_index$Gini[is.na(res_index$Gini)] <- 0.00001
  res_index$Tau[is.na(res_index$Tau)] <- 0.00001

  res_index$GiniTau <- res_index$Gini * res_index$Tau
  
  res_index$scMutScore<- 2 / (
    (1 / (coefficient_gini * res_index$GiniTau + 0.00001)) + 
    (1 / ((1 - coefficient_gini) * res_diversity$Diversity + 0.00001))
  )
  
  res_index$Diversity <- res_diversity$Diversity
  
  res_index$scMutScore <- scales::rescale(res_index$scMutScore, to = c(0, 1))
  
  res <- list(diversity = res_diversity, score = res_index, matrixD = data_cell_time_matrix)
  return(res)
}
```

# LoadData
```{r loadData}
CD34_CSM <- readRDS("../Data/CD34/CD34_CSM.rds")
CD34_SSM <- readRDS("../Data/CD34/CD34_SSM.rds")
CD34_Meta <- readRDS("../Data/CD34/CD34_meta.rds")
```

# Calculationg mutations of each cell and cells of each mutation 
```{r calculateMutPerCell}
CD34_MutPerCell <- data.frame(
  CellTag = rownames(CD34_CSM),
  MutNum_somatic = rowSums(CD34_CSM == "Mut"),
  WTNum_somatic = rowSums(CD34_CSM == "WT")
)

CD34_CellPerMut <- data.frame(
  Location = colnames(CD34_CSM),
  CellMutNum = colSums(CD34_CSM == "Mut"),
  CellWTNum = colSums(CD34_CSM == "WT")
)

cells_candidate <- CD34_MutPerCell[CD34_MutPerCell$MutNum_somatic >= 1,]$CellTag
muts_candidate <- CD34_CellPerMut[CD34_CellPerMut$CellMutNum >= 1,]$Location
CD34_CSM <- CD34_CSM[cells_candidate, muts_candidate]
```

# calMulti
```{r calMulti}
time_types <- c("ery1", "ery2", "ery3", "ery4", "ery5", "ery6",  "my1",  "my2",  "my3",  "my4", "prog", "prog_ery", "prog_my")

# Cell_Mut
CD34_Meta <- CD34_Meta[CD34_Meta$Cellbarcode %in% cells_candidate,]
CD34_cell_mut_raw <- CD34_CSM

# Mut_Time
CD34_mut_time <- as.data.frame(matrix(nrow = length(muts_candidate), ncol = length(time_types)))
rownames(CD34_mut_time) <- muts_candidate
colnames(CD34_mut_time) <- time_types

for (i in 1:nrow(CD34_mut_time)){
  mut_tmp <- rownames(CD34_mut_time)[i]
  cell_tmp <- retriveCellsByLocation(CD34_cell_mut_raw, mut_tmp)
  selected_meta_tags <- CD34_Meta[CD34_Meta$Cellbarcode %in% cell_tmp$Mut,]$Group
  
  CD34_mut_time[i,]$ery1 <- sum(str_count(selected_meta_tags, "ery1"))
  CD34_mut_time[i,]$ery2 <- sum(str_count(selected_meta_tags, "ery2"))
  CD34_mut_time[i,]$ery3 <- sum(str_count(selected_meta_tags, "ery3"))
  
  CD34_mut_time[i,]$ery4 <- sum(str_count(selected_meta_tags, "ery4"))
  CD34_mut_time[i,]$ery5 <- sum(str_count(selected_meta_tags, "ery5"))
  CD34_mut_time[i,]$ery6 <- sum(str_count(selected_meta_tags, "ery6"))
  
  CD34_mut_time[i,]$my1 <- sum(str_count(selected_meta_tags, "my1"))
  CD34_mut_time[i,]$my2 <- sum(str_count(selected_meta_tags, "my2"))
  CD34_mut_time[i,]$my3 <- sum(str_count(selected_meta_tags, "my3"))
  CD34_mut_time[i,]$my4 <- sum(str_count(selected_meta_tags, "my4"))
  
  CD34_mut_time[i,]$prog <- sum(str_count(selected_meta_tags, "prog"))
  CD34_mut_time[i,]$prog_my <- sum(str_count(selected_meta_tags, "prog_my"))
  CD34_mut_time[i,]$prog_ery <- sum(str_count(selected_meta_tags, "prog_ery"))
}

cell_time_num <- sapply(time_types, function(i) sum(str_count(CD34_Meta$Group, i)))
total_cells <- sum(cell_time_num)
cell_time_num_ratio <- cell_time_num/total_cells + 2
CD34_mut_time_nor <- sweep(CD34_mut_time, 2, log2(cell_time_num_ratio), "/")
```

# computescMutScore
```{r computescMutScore}
res_index_raw_total <- cal_scMutScore(CD34_cell_mut_raw, CD34_mut_time_nor, CD34_Meta, coefficient_gini = 0.1)

res_index_raw <- res_index_raw_total$score
res_index_raw$Cellbarcode <- rownames(res_index_raw)

res_matrix <- res_index_raw_total$matrixD

res_index <- merge(res_index_raw, CD34_Meta, by = "Cellbarcode")

selectedGroup <- c("prog", "prog_my", "prog_ery", "my1","my2",'my3','my4', "ery1", "ery2", "ery3", "ery4", "ery5", "ery6")
res_index <- res_index[res_index$Group %in% selectedGroup,]

#res_index$Group[grepl('prog|prog_my|prog_ery|mix',res_index$Group)] <- 'Prog'

res_index$CellMutTag <- factor(res_index$CellMutTag, levels = c("D_8", "D_14", "D_20"))
```

# checkIndex
```{r checkIndex}
cluster_color <- c(my1 = '#6baed6', my2 = '#4292c6',  my3 = '#2171b5',  my4 = '#084594', prog = '#e0e0e0',  prog_my = '#c6dbef', 
                   ery1 = "#bfd3e6", ery2 = "#9ebcda", ery3 = "#8c96c6", ery4 = "#8c6bb1", ery5 = "#88419d", ery6 = "#6e016b", 
                   prog_ery = "#d8daeb", mix = "#66c2a4",  Prog = '#c6dbef', ery1_2 = "#8c96c6", ery3_4 = "#8c6bb1", ery5_6 = "#6e016b")

day_color <- c(D_8 = "#c7e9c0", D_14 = "#74c476", D_20 = "#005a32")

cell_group_color <- c(Prog = "#e5f5f9", Diff = "#66c2a4", Terminal = "#006d2c")

res_index <- res_index[!is.na(res_index$scMutScore),]

ggplot(data = res_index, mapping = aes(x = CellMutTag, y = scMutScore, fill = CellMutTag)) +
  geom_boxplot(outliers = FALSE) +
  labs(x = "", y = "scMutraceScore") +
  scale_fill_manual(values = day_color) +
  theme_classic()

ggplot(data = res_index, mapping = aes(x = CellMutTag1, y = scMutScore, fill = CellMutTag1)) +
  geom_boxplot(outliers = FALSE) +
  labs(x = "", y = "scMutraceScore") +
  scale_fill_manual(values = cluster_color) +
  theme_classic()

ggplot(data = res_index, mapping = aes(x = CellMutTag, y = sumMut, fill = CellMutTag)) +
  geom_boxplot(outliers = FALSE) +
  labs(x = "", y = "scMutraceScore") +
  scale_fill_manual(values = day_color) +
  theme_classic()

ggplot(data = res_index, mapping = aes(x = CellMutTag1, y = sumMut, fill = CellMutTag1)) +
  geom_boxplot(outliers = FALSE) +
  labs(x = "", y = "scMutraceScore") +
  scale_fill_manual(values = cluster_color) +
  theme_classic()

res_index_long <- melt(res_index[,c("Gini","Tau", "scMutScore")])

ggplot(res_index_long, aes(x=value, fill=variable)) +
  geom_density(alpha=0.4) +
  theme_classic() +
  labs(x="Value", y="Density", title="Diversity Indices Distribution") +
  scale_fill_brewer(palette="Set3")
```

# scMutrce validation
```{r scMutraceValidation}
set.seed(2025)

# 1. init
data_check_CM <- CD34_cell_mut_raw
data_check_Meta <- CD34_Meta
col_check_names <- c("ery1", "ery2", "ery3", "ery4", "ery5", "ery6",  "my1",  "my2",  "my3",  "my4", "prog", "prog_ery", "prog_my")
time_types <- c("ery1", "ery2", "ery3", "ery4", "ery5", "ery6",  "my1",  "my2",  "my3",  "my4", "prog", "prog_ery", "prog_my")
cluster_color <- c(my1 = '#6baed6', my2 = '#4292c6',  my3 = '#2171b5',  my4 = '#084594', prog = '#e0e0e0',  prog_my = '#c6dbef', 
                   ery1 = "#bfd3e6", ery2 = "#9ebcda", ery3 = "#8c96c6", ery4 = "#8c6bb1", ery5 = "#88419d", ery6 = "#6e016b", 
                   prog_ery = "#d8daeb", mix = "#66c2a4",  Prog = '#c6dbef', ery1_2 = "#8c96c6", ery3_4 = "#8c6bb1", ery5_6 = "#6e016b")

day_color <- c(D_8 = "#c7e9c0", D_14 = "#74c476", D_20 = "#005a32")

cell_num <- 1
mut_num <- 1
mut_loss_ratio <- 0.5
cell_loss_ratio <- 0.5
iteration_times <- 100

# list for save data
data_scMutModel_list <- vector("list", iteration_times)

num_cells <- nrow(data_check_CM)
num_mutations <- ncol(data_check_CM)
cells_all <- rownames(data_check_CM)
muts_all <- colnames(data_check_CM)

# 2. loop
for (iter in seq_len(iteration_times)) {
  
  # 2.1 randomly loss info
  loss_cell_indices <- sample(seq_len(num_cells), ceiling(cell_loss_ratio * num_cells))
  loss_mut_indices <- sample(seq_len(num_mutations), ceiling(mut_loss_ratio * num_mutations))
  
  C_partial_missing <- data_check_CM
  # new data
  if(length(loss_cell_indices) > 0 && length(loss_mut_indices) > 0){
    C_partial_missing[loss_cell_indices, loss_mut_indices] <- "NoCall"
  }
  
  # 2.2 count cell/mut number
  MutPerCell <- rowSums(C_partial_missing == "Mut")
  CellPerMut <- colSums(C_partial_missing == "Mut")
  
  cells_candidate <- cells_all[MutPerCell >= cell_num & cells_all %in% data_check_Meta$Cellbarcode]
  cells_candidate_group <- data_check_Meta[cells_candidate, "Group"]
  muts_candidate <- muts_all[CellPerMut >= mut_num]
  
  message(paste0("Iteration: ", iter, " loss_cell_indices: ", length(loss_cell_indices), " loss_mut_indices: ", length(loss_mut_indices)))
  message(paste0("Iteration: ", iter, " cells_candidate: ", length(cells_candidate), " muts_candidate: ", length(muts_candidate)))
  
  data_cell_mut_raw_check <- C_partial_missing[cells_candidate, muts_candidate, drop = TRUE]
  
  # 2.3 Mut × Time
  cell_time_num <- sapply(col_check_names, function(i) sum(str_count(cells_candidate_group, i)))
  total_cells <- sum(cell_time_num)
  cell_time_ratio <- cell_time_num / total_cells + 2
  
  # init Mut × Time
  M_partial_missing <- matrix(0, nrow = length(muts_candidate), ncol = length(time_types),
                              dimnames = list(muts_candidate, time_types))
  
  # Calculate the number of each mutation at each time
  for (t in seq_along(time_types)) {
    time_label <- time_types[t]
    # Find out in which cells each mutation occurs
    mut_cell_list <- apply(data_cell_mut_raw_check, 2, function(x) which(x == "Mut"))
    # Count the number of times each mutation occurs at that point in time
    for (mut in muts_candidate) {
      cells_with_mut <- rownames(data_cell_mut_raw_check)[data_cell_mut_raw_check[, mut] == "Mut"]
      selected_times <- data_check_Meta$Group[data_check_Meta$Cellbarcode %in% cells_with_mut]
      M_partial_missing[mut, t] <- sum(str_count(selected_times, time_label))
    }
  }
  
  # 2.4 normalized Mut × Time
  M_partial_missing_norm <- sweep(M_partial_missing, 2, log2(cell_time_ratio), "/")
  
  # 2.5 scMutScore
  res_index_tmp <- cal_scMutScore(data_cell_mut_raw_check, M_partial_missing_norm, data_check_Meta, coefficient_gini = 0.1)$score
  res_index_tmp$iteration <- paste0("iter", iter)
  res_index_tmp <- res_index_tmp[res_index_tmp$Diversity > 0, ]
  res_index_tmp$Cellbarcode <- rownames(res_index_tmp)
  res_index_tmp$iteration <- paste0("iter", iter)
  rownames(res_index_tmp) <- NULL
  data_scMutModel_list[[iter]] <- res_index_tmp
}

# 3. merge res
data_scMutModel_res <- do.call(rbind, data_scMutModel_list)

# 4. column
data_scMutModel_res <- data_scMutModel_res %>%
  left_join(data_check_Meta, by = "Cellbarcode")

data_scMutModel_res <- data_scMutModel_res %>% dplyr::filter(Group %in% c("Prog", "prog_my", "prog_ery", "prog", "my1","my2",'my3','my4', "ery1", "ery2", "ery3", "ery4", "ery5", "ery6")) 

table(data_check_Meta$Group)
# keep 100 cells for each cell type

data_scMutModel_res$GroupQun <- as.character(data_scMutModel_res$Group)

data_scMutModel_res$GroupQun[grepl("ery1|ery2", data_scMutModel_res$Group)] <- "ery1_2"
data_scMutModel_res$GroupQun[grepl("ery3|ery4", data_scMutModel_res$Group)] <- "ery3_4"
data_scMutModel_res$GroupQun[grepl("ery5|ery6", data_scMutModel_res$Group)] <- "ery5_6"

data_scMutModel_res$Group <- factor(data_scMutModel_res$Group, levels = c("Prog", "prog", "prog_my", "my1", "my2", "my3", "my4", "prog_ery", "ery1", "ery2", "ery3", "ery4", "ery5", "ery6"))
data_scMutModel_res$GroupQun <- factor(data_scMutModel_res$GroupQun, levels = c("Prog", "prog", "prog_my", "my1", "my2", "my3", "my4",  "prog_ery",  "ery1_2", "ery3_4", "ery5_6"))
data_scMutModel_res$CellMutTag <- factor(data_scMutModel_res$CellMutTag, levels = c("D_8", "D_14", "D_20"))

# 5. plot
data_scMutModel_res_summary <- data_scMutModel_res %>%
  dplyr::group_by(iteration, GroupQun) %>%
  dplyr::summarise(mean_scMutScore = mean(scMutScore, na.rm = TRUE), mean_EpiTraceAge = mean(EpiTraceAge_iterative, na.rm = TRUE)) %>%
  #dplyr::summarise(mean_EpiTraceAge = mean(EpiTraceAge_iterative, na.rm = TRUE)) %>%
  dplyr::ungroup()

data_scMutModel_res_summary <- data_scMutModel_res_summary %>%
  dplyr::mutate(
    mean_scMutScore_scaled = scales::rescale(mean_scMutScore, to = c(0, 1)),
    mean_EpiTraceAge_scaled = scales::rescale(mean_EpiTraceAge, to = c(0, 1))
  )

data_scMutModel_res_summary_Day <- data_scMutModel_res %>%
  dplyr::group_by(iteration, CellMutTag) %>%
  dplyr::summarise(mean_scMutScore = mean(scMutScore, na.rm = TRUE)) %>%
  dplyr::ungroup()

data_scMutModel_res_summary_Day <- data_scMutModel_res_summary_Day %>%
  dplyr::mutate(
    mean_scMutScore_scaled = scales::rescale(mean_scMutScore, to = c(0, 1))
  )

data_stability <- data_scMutModel_res %>%
  dplyr::group_by(GroupQun) %>%
  dplyr::summarise(
    mean_score = mean(scMutScore, na.rm = TRUE),
    sd_score = sd(scMutScore, na.rm = TRUE),
    cv_score = sd_score / mean_score
  )

p_scMutrace_iter_GroupQun <- ggplot(data = data_scMutModel_res_summary, mapping = aes(x = GroupQun, y = mean_scMutScore, fill = GroupQun)) +
  #geom_violin(trim = TRUE, alpha = 0.6) + 
  geom_boxplot(outliers = FALSE) +
  ylim(0.4, 0.9) +
  labs(x = "", y = "scMutraceScore") +
  scale_fill_manual(values = cluster_color) +
  theme_classic()

p_scMutrace_iter_GroupQunScaled <- ggplot(data = data_scMutModel_res_summary, mapping = aes(x = GroupQun, y = mean_scMutScore_scaled, fill = GroupQun)) +
  #geom_violin(trim = TRUE, alpha = 0.6) + 
  geom_boxplot(outliers = FALSE) +
  ylim(0, 1) +
  labs(x = "", y = "mean_scMutScore_scaled") +
  scale_fill_manual(values = cluster_color) +
  theme_classic()

 p_scMutrace_iter_Day <- ggplot(data = data_scMutModel_res_summary_Day, mapping = aes(x = CellMutTag, y = mean_scMutScore, fill = CellMutTag)) +
  #geom_violin(trim = TRUE, alpha = 0.6) + 
  geom_boxplot(outliers = FALSE) +
  ylim(0.4, 0.9) +
  labs(x = "", y = "scMutraceScore") +
  scale_fill_manual(values = day_color) +
  theme_classic()
 
 p_scMutrace_iter_Day_scaled <- ggplot(data = data_scMutModel_res_summary_Day, mapping = aes(x = CellMutTag, y = mean_scMutScore_scaled, fill = CellMutTag)) +
  #geom_violin(trim = TRUE, alpha = 0.6) + 
  geom_boxplot(outliers = FALSE) +
  ylim(0, 1) +
  labs(x = "", y = "mean_scMutScore_scaled") +
  scale_fill_manual(values = day_color) +
  theme_classic()

df_iter_frac <- data_scMutModel_res %>%
  group_by(GroupQun, CellMutTag) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(GroupQun) %>%
  mutate(prop = n / sum(n))

p_iter_cellfrac <- ggplot(df_iter_frac, aes(x = GroupQun, y = prop, fill = CellMutTag)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = day_color) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

p_scMutrace_iter_Day + p_scMutrace_iter_Day_scaled + p_scMutrace_iter_GroupQun + p_scMutrace_iter_GroupQunScaled + p_iter_cellfrac
```

# randomMutNum
```{r randomMutNum}
sample_size <- 100
iter_num <- 1:100
data_random_mutNum <- data.frame(iteration_num = iter_num, CD34_800_Day08 = 0,
                                 CD34_800_Day14 = 0, CD34_800_Day20 = 0)

CD34_Meta_selectedRandom <- CD34_Meta[CD34_Meta$Cellbarcode %in% rownames(CD34_CSM),]

for (iter in iter_num){
  cell_08 <- CD34_Meta_selectedRandom %>% filter(CellMutTag == "D_8") %>% pull(Cellbarcode) %>% sample(., sample_size)
  cell_14 <- CD34_Meta_selectedRandom %>% filter(CellMutTag == "D_14") %>% pull(Cellbarcode) %>% sample(., sample_size)
  cell_20 <- CD34_Meta_selectedRandom %>% filter(CellMutTag == "D_20") %>% pull(Cellbarcode) %>% sample(., sample_size)
  mut_08 <- retriveLocsByCells(CD34_CSM, cell_08)$Mut
  mut_14 <- retriveLocsByCells(CD34_CSM, cell_14)$Mut
  mut_20 <- retriveLocsByCells(CD34_CSM, cell_20)$Mut
  data_random_mutNum[iter, "CD34_800_Day08"] <- length(mut_08)
  data_random_mutNum[iter, "CD34_800_Day14"] <- length(mut_14)
  data_random_mutNum[iter, "CD34_800_Day20"] <- length(mut_20)
}

data_random_mutNum_long <- data_random_mutNum %>%
  pivot_longer(
    cols = -iteration_num,
    names_to = "Sample",
    values_to = "Mutation_Number"
  )

p_randomMutNum_est <- ggplot(data_random_mutNum_long, aes(x = Sample, y = Mutation_Number, fill = Sample)) +
  geom_boxplot(outlier.shape = NA, width = 0.7) +
  scale_fill_manual(values = c(CD34_800_Day08 = "#c7e9c0", CD34_800_Day14 = "#74c476", CD34_800_Day20 = "#005a32")) +
  #geom_jitter(width = 0.15, size = 1.5, alpha = 0.6) +
  theme_classic() +
  labs(
    x = "",
    y = "Number of Mutations"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )
p_randomMutNum_est
```

# outputFigures
```{r outputFigures}
res_index <- res_index[res_index$Diversity > 0, ]

res_index %>% dplyr::filter(Group %in% c("Prog", "prog_my", "prog_ery", "prog", "my1","my2",'my3','my4'))  %>% dplyr::group_by(clone,Group,cell_day) %>% dplyr::summarise(meanscMutScore=mean(scMutScore)) -> res_index_meta_summary_scMutScore
res_index_meta_summary_scMutScore$CultureDay <- paste("D_", res_index_meta_summary_scMutScore$cell_day, sep = "")

res_index_meta_summary_scMutScore$cell_group <- 'Prog'
res_index_meta_summary_scMutScore$cell_group[grepl('my1',res_index_meta_summary_scMutScore$Group)] <- 'Diff'
res_index_meta_summary_scMutScore$cell_group[grepl('my2|my3|my4',res_index_meta_summary_scMutScore$Group)] <- 'Terminal'
res_index_meta_summary_scMutScore$cell_group <- factor(res_index_meta_summary_scMutScore$cell_group,levels=c('Prog','Diff','Terminal'))

res_index$GroupQun <- as.character(res_index$Group)

res_index$GroupQun[grepl("ery1|ery2", res_index$Group)] <- "ery1_2"
res_index$GroupQun[grepl("ery3|ery4", res_index$Group)] <- "ery3_4"
res_index$GroupQun[grepl("ery5|ery6", res_index$Group)] <- "ery5_6"

res_index$Group <- factor(res_index$Group, levels = c("Prog", "prog", "prog_my", "my1", "my2", "my3", "my4", "prog_ery", "ery1", "ery2", "ery3", "ery4", "ery5", "ery6"))
res_index$GroupQun <- factor(res_index$GroupQun, levels = c("Prog", "prog", "prog_my", "my1", "my2", "my3", "my4",  "prog_ery",  "ery1_2", "ery3_4", "ery5_6"))
res_index_meta_summary_scMutScore$CultureDay <- factor(res_index_meta_summary_scMutScore$CultureDay, levels = c("D_8", "D_14", "D_20"))

CD34_Meta_selected <- CD34_Meta[CD34_Meta$Cellbarcode %in% res_index$Cellbarcode,]
CD34_Meta_selected$GroupQun <- CD34_Meta_selected$Group
CD34_Meta_selected$GroupQun[grepl("ery1|ery2", CD34_Meta_selected$Group)] <- "ery1_2"
CD34_Meta_selected$GroupQun[grepl("ery3|ery4", CD34_Meta_selected$Group)] <- "ery3_4"
CD34_Meta_selected$GroupQun[grepl("ery5|ery6", CD34_Meta_selected$Group)] <- "ery5_6"

UMAP_Day8 <- ggplot(data = CD34_Meta_selected) +
  geom_point(aes(x = x, y = y), color = "grey90", size = 1.5) +
  geom_point(data = subset(CD34_Meta_selected, cell_day == 8),
             aes(x = x, y = y, color = Group), size = 1.5, alpha = 0.5) +
  scale_color_manual(values = cluster_color) +
  xlab("") + ylab("") +
  theme_classic()

UMAP_Day14 <- ggplot(data = CD34_Meta_selected) +
  geom_point(aes(x = x, y = y), color = "grey90", size = 1.5) +
  geom_point(data = subset(CD34_Meta_selected, cell_day == 14),
             aes(x = x, y = y, color = Group), size = 1.5, alpha = 0.5) +
  scale_color_manual(values = cluster_color) +
  xlab("") + ylab("") +
  theme_classic()

UMAP_Day20 <- ggplot(data = CD34_Meta_selected) +
  geom_point(aes(x = x, y = y), color = "grey90", size = 1.5) +
  geom_point(data = subset(CD34_Meta_selected, cell_day == 20),
             aes(x = x, y = y, color = Group), size = 1.5, alpha = 0.5) +
  scale_color_manual(values = cluster_color) +
  xlab("") + ylab("") +
  theme_classic()

p_UMAP_Days <- ggplot(data = CD34_Meta_selected, mapping = aes(x = x, y = y, color = CellMutTag)) +
  geom_point(size = 1.5) +
  scale_color_manual(values = day_color) +
  xlab("") + ylab("") +
  theme_classic()

p_UMAP_Groups <- ggplot(data = CD34_Meta_selected, mapping = aes(x = x, y = y, color = Group)) +
  geom_point(size = 1.5) +
  scale_color_manual(values = cluster_color) +
  xlab("") + ylab("") +
  theme_classic()

p_UMAP_GroupsQun <- ggplot(data = CD34_Meta_selected, mapping = aes(x = x, y = y, color = GroupQun)) +
  geom_point(size = 1.5) +
  scale_color_manual(values = cluster_color) +
  xlab("") + ylab("") +
  theme_classic()

p_UMAP_pseudutime_my <- ggplot(data = CD34_Meta_selected, mapping = aes(x = x, y = y, color =  pseudutime_my)) +
  geom_point(size = 1.5) +
  #scale_color_manual(values = day_color) +
  scale_color_viridis(option = "plasma") +
  xlab("") + ylab("") +
  theme_classic()

p_UMAP_pseudutime_ery <- ggplot(data = CD34_Meta_selected, mapping = aes(x = x, y = y, color =  pseudutime_ery)) +
  geom_point(size = 1.5) +
  #scale_color_manual(values = day_color) +
  scale_color_viridis(option = "plasma") +
  xlab("") + ylab("") +
  theme_classic()

# plot scMutScore by days
p_scMutScorebydays <- ggplot(res_index, aes(x=as.factor(CellMutTag), y=scMutScore, fill = CellMutTag)) + 
  scale_fill_manual(values = day_color) + geom_boxplot(outlier.alpha = 0) +
  theme_classic()

# plot scMutScore by cell types
p_scMutScorebycelltypes <- ggplot(res_index, aes(x=as.factor(Group), y=scMutScore, fill = Group)) + 
  scale_fill_manual(values = cluster_color) + geom_boxplot(outlier.alpha = 0) +
  theme_classic()

p_scMutScorebycelltypesQun <- ggplot(res_index, aes(x=as.factor(GroupQun), y=scMutScore, fill = GroupQun)) + 
  scale_fill_manual(values = cluster_color) + geom_boxplot(outlier.alpha = 0) +
  ylim(0,1) +
  theme_classic()

p_EpiScorebyCelltype <- ggplot(res_index, aes(x=as.factor(Group), y=EpiTraceAge_iterative, fill = Group)) + 
  scale_fill_manual(values = cluster_color) + geom_boxplot(outlier.alpha = 0) +
  theme_classic()

p_EpiScorebyCelltypeQun <- ggplot(res_index, aes(x=as.factor(GroupQun), y=EpiTraceAge_iterative, fill = GroupQun)) + 
  scale_fill_manual(values = cluster_color) + geom_boxplot(outlier.alpha = 0) +
  theme_classic()

p_CloneLevelByCellGroup <- ggplot(res_index_meta_summary_scMutScore, mapping = aes(x = as.factor(cell_group), y = meanscMutScore, fill = cell_group)) +
  geom_boxplot(outliers = TRUE) +
  geom_line(aes(group = clone),  alpha = 0.1, linetype='dashed') +
  scale_fill_manual(values = cell_group_color) +
  labs(x = "", y = "scMutraceScore") +
  theme_classic()

p_CloneLevelByDaysSplitbyCellgroup <- ggplot(res_index_meta_summary_scMutScore,aes(x=factor(cell_day),y= meanscMutScore)) + 
  geom_line(aes(group=clone),size=0.5,alpha=0.1,linetype='dashed') + geom_boxplot(outlier.alpha = 1,fill='white',width=0.5) + 
  facet_wrap(~cell_group)  + theme_classic() + xlab('Days in culture') + ylab('Mean scMutScore') + theme(text=element_text(size=20))

p_CloneLevelByDaysSplitbyCellType <-  ggplot(res_index_meta_summary_scMutScore,aes(x=factor(cell_day),y= meanscMutScore)) + 
  geom_line(aes(group=clone),size=0.5,alpha=0.1,linetype='dashed')  + geom_boxplot(outlier.alpha = 1,fill='white',width=0.5) + 
  facet_wrap(~Group)  + theme_classic() + xlab('Days in culture') + ylab('Mean scMutScore') + theme(text=element_text(size=20))

p_CloneLevelByDays <- ggplot(res_index_meta_summary_scMutScore, mapping = aes(x = as.factor(CultureDay), y = meanscMutScore, fill = CultureDay)) +
  geom_boxplot(outliers = TRUE) +
  geom_line(aes(group = clone),  alpha = 0.1,linetype='dashed') +
  scale_fill_manual(values = day_color) +
  labs(x = "", y = "scMutraceScore") +
  theme_classic()

# EpiTraceAge
res_index %>% dplyr::group_by(clone,Group,cell_day) %>% dplyr::summarise(meanEpi=mean(EpiTraceAge_iterative)) -> res_index_meta_summary_EpiTraceAge
res_index_meta_summary_EpiTraceAge$cell_group <- 'Prog'
res_index_meta_summary_EpiTraceAge$cell_group[grepl('my1',res_index_meta_summary_EpiTraceAge$Group)] <- 'Diff'
res_index_meta_summary_EpiTraceAge$cell_group[grepl('my2|my3|my4',res_index_meta_summary_EpiTraceAge$Group)] <- 'Terminal'
res_index_meta_summary_EpiTraceAge$cell_group <- factor(res_index_meta_summary_EpiTraceAge$cell_group,levels=c('Prog','Diff','Terminal'))

p_CloneLevelByCellGroup_EpiTraceAge <- ggplot(res_index_meta_summary_EpiTraceAge, mapping = aes(x = as.factor(cell_group), y = meanEpi, fill = cell_group)) +
  geom_boxplot(outliers = TRUE) +
  geom_line(aes(group = clone),  alpha = 0.1, linetype='dashed') +
  scale_fill_manual(values = cell_group_color) +
  labs(x = "", y = "EpiTraceAge") +
  theme_classic()

p_CloneLevelByCellGroup_scMutraceScore <- ggplot(res_index_meta_summary_scMutScore, mapping = aes(x = as.factor(cell_group), y = meanscMutScore, fill = cell_group)) +
  geom_boxplot(outliers = TRUE) +
  geom_line(aes(group = clone),  alpha = 0.1, linetype='dashed') +
  scale_fill_manual(values = cell_group_color) +
  labs(x = "", y = "EpiTraceAge") +
  theme_classic()

p_pseudotimeByDaysEry <- ggplot(res_index, aes(x=as.factor(CellMutTag), y=pseudutime_ery, fill = CellMutTag)) + 
     scale_fill_manual(values = day_color) + geom_boxplot(outlier.alpha = 0) +
     theme_classic()

p_pseudotimeByDaysMy <- ggplot(res_index, aes(x=as.factor(CellMutTag), y=pseudutime_my, fill = CellMutTag)) + 
     scale_fill_manual(values = day_color) + geom_boxplot(outlier.alpha = 0) +
     theme_classic()

p_pseudotimeByGroupQunEry <- ggplot(res_index, aes(x=as.factor(GroupQun), y=pseudutime_ery, fill = GroupQun)) + 
     scale_fill_manual(values = cluster_color) + geom_boxplot(outlier.alpha = 0) +
     theme_classic()

p_pseudotimeByGroupQunMy <- ggplot(res_index, aes(x=as.factor(GroupQun), y=pseudutime_my, fill = GroupQun)) + 
     scale_fill_manual(values = cluster_color) + geom_boxplot(outlier.alpha = 0) +
     theme_classic()

p_UMAP_scMutrace <- ggplot(data = res_index, mapping = aes(x = x, y = y, color =  scMutScore)) +
  geom_point(size = 1.5) +
  #scale_color_manual(values = day_color) +
  scale_color_viridis(option="rocket") +
  xlab("") + ylab("") +
  theme_classic()

df_plot <- res_index %>%
  count(CellMutTag, GroupQun) %>%
  complete(
    CellMutTag,
    GroupQun = c(
      "prog", "prog_my",
      "my1", "my2", "my3", "my4",
      "prog_ery", "ery1_2", "ery3_4", "ery5_6"
    ),
    fill = list(n = 0)
  )

df_plot$GroupQun <- factor(
  df_plot$GroupQun,
  levels = c(
    "prog", "prog_my",
    "my1", "my2", "my3", "my4",
    "prog_ery", "ery1_2", "ery3_4", "ery5_6"
  )
)

ggplot(df_plot, aes(x = CellMutTag, y = n, fill = GroupQun)) +
  geom_col(position = "dodge") +
  labs(
    x = "CellMutTag",
    y = "Cell count",
    fill = "GroupQun"
  ) +
  scale_fill_manual(values = cluster_color) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

df_mean <- res_index %>%
  group_by(GroupQun) %>%
  summarise(
    mean_scMutScore = mean(scMutScore, na.rm = TRUE),
    mean_EpiTraceAge  = mean(EpiTraceAge_iterative, na.rm = TRUE),
    mean_pseudutime_my    = mean(pseudutime_my, na.rm = TRUE),
    mean_pseudutime_ery    = mean(pseudutime_ery, na.rm = TRUE),
    n = n()
  )

df_frac <- res_index %>%
  group_by(GroupQun, CellMutTag) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(GroupQun) %>%
  mutate(prop = n / sum(n))

p_cellfrac <- ggplot(df_frac, aes(x = GroupQun, y = prop, fill = CellMutTag)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_fill_manual(values = day_color) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()

p_UMAP_Days
p_UMAP_Groups
p_UMAP_GroupsQun
p_scMutScorebydays
p_scMutScorebycelltypes
p_scMutScorebycelltypesQun
p_CloneLevelByCellGroup
p_EpiScorebyCelltype
p_EpiScorebyCelltypeQun
p_CloneLevelByDaysSplitbyCellgroup
p_CloneLevelByDaysSplitbyCellType
p_CloneLevelByDays
p_CloneLevelByCellGroup_EpiTraceAge
p_CloneLevelByCellGroup_scMutraceScore
p_pseudotimeByDaysEry
p_pseudotimeByDaysMy
p_pseudotimeByGroupQunEry
p_pseudotimeByGroupQunMy
p_UMAP_pseudutime_my
p_UMAP_pseudutime_ery
p_UMAP_scMutrace
p_cellfrac
```

# correlation of scMutrace and EpiAge
```{r correlation_scMutrace_EpiAge}
data_scMutModel_res_summary_mean <- data_scMutModel_res_summary %>%
  dplyr::group_by(GroupQun) %>%
  dplyr::summarise(mean_scMutScoreGroup = mean(mean_scMutScore, na.rm = TRUE), mean_EpiTraceAgeGroup = mean(mean_EpiTraceAge, na.rm = TRUE)) %>%
  dplyr::ungroup()

data_scMutModel_res_summary_mean_rmprog <- data_scMutModel_res_summary_mean[data_scMutModel_res_summary_mean$GroupQun != "prog", ]
plot(data_scMutModel_res_summary_mean$mean_scMutScoreGroup, data_scMutModel_res_summary_mean$mean_EpiTraceAgeGroup)
plot(data_scMutModel_res_summary_mean_rmprog$mean_scMutScoreGroup, data_scMutModel_res_summary_mean_rmprog$mean_EpiTraceAgeGroup)
cor.test(data_scMutModel_res_summary_mean$mean_scMutScoreGroup, data_scMutModel_res_summary_mean$mean_EpiTraceAgeGroup)
cor.test(data_scMutModel_res_summary_mean_rmprog$mean_scMutScoreGroup, data_scMutModel_res_summary_mean_rmprog$mean_EpiTraceAgeGroup)

cor.test(data_scMutModel_res_summary$mean_scMutScore, data_scMutModel_res_summary$mean_EpiTraceAge)
data_scMutModel_res_summary_rmprog <- data_scMutModel_res_summary[data_scMutModel_res_summary$GroupQun != "prog", ]
cor.test(data_scMutModel_res_summary_rmprog$mean_scMutScore, data_scMutModel_res_summary_rmprog$mean_EpiTraceAge)
plot(data_scMutModel_res_summary_rmprog$mean_scMutScore, data_scMutModel_res_summary_rmprog$mean_EpiTraceAge)
```

# savePic
```{r saveData, eval=FALSE}
pdf("../Figure/CD34/p_UMAP_Days.pdf", width = 4.47, height = 3.20)
p_UMAP_Days
dev.off()

pdf("../Figure/CD34/p_UMAP_Groups.pdf", width = 4.47, height = 3.20)
p_UMAP_Groups
dev.off()

pdf("../Figure/CD34/p_UMAP_pseudutime_my.pdf", width = 4.47, height = 3.20)
p_UMAP_pseudutime_my
dev.off()

pdf("../Figure/CD34/p_UMAP_pseudutime_ery.pdf", width = 4.47, height = 3.20)
p_UMAP_pseudutime_ery
dev.off()

pdf("../Figure/CD34/p_scMutScorebydays.pdf", width = 4.47, height = 3.20)
p_scMutScorebydays
dev.off()

pdf("../Figure/CD34/p_scMutScorebycelltypes.pdf", width = 4.47, height = 3.20)
p_scMutScorebycelltypesQun
dev.off()

pdf("../Figure/CD34/p_EpiScorebyCelltype.pdf", width = 4.47, height = 3.20)
p_EpiScorebyCelltypeQun
dev.off()

pdf("../Figure/CD34/p_pseudotimeByDaysEry.pdf", width = 4.47, height = 3.20)
p_pseudotimeByDaysEry
dev.off()

pdf("../Figure/CD34/p_pseudotimeByDaysMy.pdf", width = 4.47, height = 3.20)
p_pseudotimeByDaysMy
dev.off()

pdf("../Figure/CD34/p_pseudotimeByGroupQunEry.pdf", width = 4.47, height = 3.20)
p_pseudotimeByGroupQunEry
dev.off()

pdf("../Figure/CD34/p_pseudotimeByGroupQunMy.pdf", width = 4.47, height = 3.20)
p_pseudotimeByGroupQunMy
dev.off()

pdf("../Figure/CD34/p_cellfracbylineage.pdf", width = 4.47, height = 3.20)
p_cellfrac
dev.off()

pdf("../Figure/CD34/p_scMutrace_iter_Day.pdf", width = 4.47, height = 3.20)
p_scMutrace_iter_Day_scaled
dev.off()

pdf("../Figure/CD34/p_scMutrace_iter_GroupQun.pdf", width = 4.47, height = 3.20)
p_scMutrace_iter_GroupQunScaled
dev.off()

pdf("../Figure/CD34/p_iter_cellfrac.pdf", width = 4.47, height = 3.20)
p_iter_cellfrac
dev.off()

pdf("../Figure/CD34/p_randomMutNum_est.pdf", width = 4.47, height = 3.20)
p_randomMutNum_est
dev.off()

```

# sessionInfo
```{r sessionInfo}
sessionInfo()
```

